### ISSUE TITLE
EPG not working

### ISSUE THREAD

**Issue by bruno-briner** [rbuehlma/pvr.zattoo#101]
It seems that the EPG is not working.

Looking in the kodi log I see a lot of instances like:

ERROR: CCurlFile::Open failed with code 503 for https://zattoo.buehlmann.net/epg/api/Epg/CH/ea8...dc8/4seven_uk/1...0/1...0:

**Comment by rbuehlma** [comment]
Thanks for reporting. This is fixed now.
