### ISSUE TITLE
1080p support

### ISSUE THREAD

**Issue by Unkn0wn-MDCLXIV** [rbuehlma/pvr.zattoo#108]
I have zattoo ultimate, which supports 1080p, but unfortunately all channels are 720p only.

**Comment by rbuehlma** [comment]
Please try to set the "Max. Bandwidth" of inputstream.adaptive to a very high value. If that works, you can change it back to 0 and it will still work. It's a bug in the configuration of inputstream.adaptive

**Comment by Unkn0wn-MDCLXIV** [comment]
Quick and easy.
Thanks, it worked.

**Comment by popy2k14** [comment]
Hey guys, also stucked at 720p, already set the inputstream adaptive to "100000000" (1000 Mbit/s) which should be sufficent.
This does'nt solved the issue.

Which streaming method must i use in the plugin settings to get 1080p? (hls/dash_dash_widevine)?

Any hints how i can fix this issue?

**Comment by popy2k14** [comment]
Dont know wha, but dirst it didnt work (also after restarting kodi), but now it works.
I have now reverted the setting to 0 and it works.
Hope it lasts :-)

thx
