### ISSUE TITLE
Crash on Voidlinux v18.1.21-Leia

### ISSUE THREAD

**Issue by teldra** [rbuehlma/pvr.zattoo#109]
I try to update pvr.zatto to newest version in Voidlinux for Leia.
Kodi is crashing, when I enable the plugin and enter my credentials.
(This version worked fine: https://github.com/void-linux/void-packages/blob/master/srcpkgs/kodi-addon-pvr-zattoo/template)

Attached are buildlog and crash message:
https://gist.github.com/teldra/1e0510813d87cb4fda3e8e50ef9da65d

**Comment by rbuehlma** [comment]
Could you provide a complete debug-log and if possible, also a stack trace.

**Comment by teldra** [comment]
Added to https://gist.github.com/teldra/1e0510813d87cb4fda3e8e50ef9da65d

**Comment by rbuehlma** [comment]
I'm not able to reproduce that issue on my system (Ubuntu Linux).
Could you provide the output of

`curl https://zattoo.com/token-46a1dfccbd4c3bdaf6182fea8f8aea3f.json`

It seems to be a problem when parsing this file.

**Comment by teldra** [comment]
```
$ curl https://zattoo.com/token-46a1dfccbd4c3bdaf6182fea8f8aea3f.json
{"success": true, "session_token": "4d424025c93b4d3cc6efcb7ac6d8ea1e"}%
```

**Comment by rbuehlma** [comment]
Ok, that is the expected outcome. It might be due to the rapidjson version. In your case, the version installed on the system is used which is an older one than the one that would be fetched if none is installed.

Could you try to build and test this branch: https://github.com/rbuehlma/pvr.zattoo/tree/bugfix/void_linux_build

**Comment by teldra** [comment]
Voidlinux ships rapidjson-1.1.0 and is used to build pvr.zattoo.
Do I need building pvr.zattoo from the testbranch then?

**Comment by teldra** [comment]
If i build it with your testbranch, its also crashing.

**Comment by rbuehlma** [comment]
Yeah, it probably still used the installed rapidjson version. Would it be possible to temporary uninstall the system rapidjson, rebuild the addon and retry? I'm not sure if the rapidjson version provided by Kodi has somehow been altered.

**Comment by teldra** [comment]
Splendid! When I compile Kodi with it's provided rapidjson, it works fine!
Thank you for helping me!

**Comment by rbuehlma** [comment]
Great to hear it worked. I fear there is not much I can do in the addon.
