### ISSUE TITLE
project status

### ISSUE THREAD

**Issue by buhtz** [rbuehlma/pvr.zattoo#11]
Following the fork graph this repo lookls like the youngest one. Is this the current official rep for Zattoo PVR?

The forum thread on kodi nerds give different informations about it

https://www.kodinerds.net/index.php/Thread/49569-Zattoo-PVR-Client/?postID=275151#post275151

**Comment by rbuehlma** [comment]
This thread is the current:
https://www.kodinerds.net/index.php/Thread/58635-PVR-Addon-f%C3%BCr-Zattoo-und-Reseller/
