### ISSUE TITLE
replay issue

### ISSUE THREAD

**Issue by oxyrev** [rbuehlma/pvr.zattoo#112]
I'm using salt tv, and everything works great expect replay, 
it seems now only v3 api works for it, is there anything i can do to force the old api/some minor change that can be made to get this feature back?
other more or less related, question i see the v3 api branch, it it supposed to be released for leila or there are some prerequisite that will make it work just for matrix?

and thanks for the great work!

**Comment by rbuehlma** [comment]
Unfortunately, there was quite a lot of refactoring required to use the v3 api. This change will therefore not be ported to Leia but it seems that Matrix will soon be released. If you want to try the change on Matrix, depending on your system you could use one of the following Addon builds:
https://jenkins.kodi.tv/blue/organizations/jenkins/rbuehlma%2Fpvr.zattoo/detail/PR-111/7/artifacts

**Comment by oxyrev** [comment]
thanks, ok i see any effort will be quite a waste of resources, if i might, what do you use as reference for v3 api? i've seen around some project/unofficial api, so that i can start getting familiar with it, hopefully in the future I might be able to offer my hand

**Comment by rbuehlma** [comment]
I'm not aware of any documentation of the API. Most of the information, I get by inspecting the requests made by the browser.
