### ISSUE TITLE
Addon not working anymore since today

### ISSUE THREAD

**Issue by cstrassmair** [rbuehlma/pvr.zattoo#114]
Zattoo PVR Addon
Kodi Leia
Latest Version installed via Kodinerds Repo

Red Icon appears
Log writes
Zattoo PVR Client: Unable to find token-*.json in /app-fceefecf7a898873afd8.js
And its not loading anything

**Comment by djraw** [comment]
Same here. But I guess it‘s already been worked on since there is a new branch addressing this. Thanks in advance :)

**Comment by phillippc** [comment]
Anyway someone can add this as an update to the libreelec addon repos? I cant update this manually on my libreelec :-( Thanks for the great work!

**Comment by djraw** [comment]
@phillippc I got the same issue. Just tried if I could compile like the steps in the readme. Unfortunately it doesn‘t work on a standard libreELEC build.
I think we need to add an issue in their repo to have them compile it for us.

@rbuehlma do you know how to compile the fixed addon for libreelec?

Edit: I just checked the libreelec github repo and their forum, but I don‘t get how I can open an issue to let them know about this. I hope there will be a fast update to the zattooHiQ addon to use that until the pvr addon gets fixed.

**Comment by rbuehlma** [comment]
The fix has been merged for Leia and Matrix. The official Kodi repo will be updated automatically. Other platforms will need to update the addon on their own.
