### ISSUE TITLE
it seems I'm fetching the wrong program ID

### ISSUE THREAD

**Issue by oxyrev** [rbuehlma/pvr.zattoo#117]
Hi, 
I'm using the great addon with salt tv, however replay doesn't work at all. 
it seems the id i get for the transmission 

as example, I'm trying to watch Handico today (27.02.2021) on rsi la1 at 10.15am
if i check with my browser i get this infos:

`{"i_url":"http://images.zattic.com/cms/1b0a02eefbc35dd97922/format_480x360.jpg","ry_u":1615022400,"cc":[],"e_no":null,"rg_u":1615022400,"et":"Malformazioni","i_t":"1b0a02eefbc35dd97922","id":210499741,"tms_id":null,"s_no":null,"c":["Bambini"],"e":1614417600,"g":["Giovent\u00f9"],"i":"cms/1b0a02eefbc35dd97922/format_480x360.jpg","ser_e":false,"ser_i_t":null,"s":1614417300,"t":"Handico","c_ids":[2],"r_e":true}`

therefore the id is 210499741 

checking the kodi log i get instead 211259521 I assume therefore that the issue might be there, is maybe linked to salt vs real zattoo?

here is the snipped of the log:

```
DEBUG <general>: AddOnLog: pvr.zattoo: Get timeshift url for channel rsi-la1 and program 211259521
DEBUG <general>: AddOnLog: pvr.zattoo: Http-Request: POST https://tv.salt.ch/zapi/v3/watch/replay/rsi-la1/211259521.
DEBUG <general>: CurlFile::Open(0xad8ad8f0) https://tv.salt.ch/zapi/v3/watch/replay/rsi-la1/211259521
DEBUG <general>: easy_acquire - Created session to https://tv.salt.ch
ERROR <general>: AddOnLog: pvr.zattoo: Open URL failed with 403.
ERROR <general>: AddOnLog: pvr.zattoo: Got 403. Try to re-init session.
DEBUG <general>: AddOnLog: pvr.zattoo: Send hello.
DEBUG <general>: AddOnLog: pvr.zattoo: Http-Request: POST https://tv.salt.ch/zapi/v3/session/hello.
DEBUG <general>: CurlFile::Open(0xadaad898) https://tv.salt.ch/zapi/v3/session/hello
ERROR <general>: AddOnLog: pvr.zattoo: Open URL failed with 403.
 INFO <general>: AddOnLog: pvr.zattoo: Hello failed.
DEBUG <general>: AddOnLog: pvr.zattoo: Http-Request: GET https://tv.salt.ch/zapi/v3/session.
DEBUG <general>: CurlFile::Open(0xad8ad8f0) https://tv.salt.ch/zapi/v3/session
DEBUG <general>: AddOnLog: pvr.zattoo: Got cookie: beaker.session.id.
DEBUG <general>: AddOnLog: pvr.zattoo: Got new beaker.session.id: 3a9c8..
 INFO <general>: AddOnLog: pvr.zattoo: Current country code: CH
 INFO <general>: AddOnLog: pvr.zattoo: Service region country: 
 INFO <general>: AddOnLog: pvr.zattoo: Stream type: dash
 INFO <general>: AddOnLog: pvr.zattoo: Recall are enabled
 INFO <general>: AddOnLog: pvr.zattoo: Recordings are enabled
DEBUG <general>: AddOnLog: pvr.zattoo: Http-Request: POST https://tv.salt.ch/zapi/v3/watch/replay/rsi-la1/211259521.
DEBUG <general>: CurlFile::Open(0xad8ad8f0) https://tv.salt.ch/zapi/v3/watch/replay/rsi-la1/211259521
ERROR <general>: AddOnLog: pvr.zattoo: Open URL failed with 403.
ERROR <general>: GetEpgTagStreamProperties: Add-on 'Zattoo PVR Add-on:connected' returned an error: the command failed
```

thank you again for your time and the great addon!

**Comment by rbuehlma** [comment]
Thanks for reporting this. Are you  using the enhanced EPG provider? Could you provide the complete log? Until now, I assumed that the EPG only differs per country. If it also differs per reseller. I would have to find another way to enhance the EPG.

**Comment by oxyrev** [comment]
I was using the enhanced EPG provider, then i reverted it (however i didn't clean up anything)
so right now it is not enabled 
here is the full log let me know if i need to enable the debug log from the beginning i just enabled it before trying to replay again

[kodi.log](https://github.com/rbuehlma/pvr.zattoo/files/6054220/kodi.log)

thanks again

**Comment by rbuehlma** [comment]
You can try to clear the EPG Data in Kodi while having the enhanced EPG service disabled. Does replay work then?

And when you are using the enhanced EPG service, are only some EPG entries not working for replay or all of them?

Also, could you provide me the content of this url:

https://zattoo.com/zapi/v3/cached/4e46d92ee4db8e8715b6d833a26f5b11/guide?start=1614394800&end=1614481200

**Comment by oxyrev** [comment]
this is what i get from 
https://tv.salt.ch/zapi/v3/cached/4e46d92ee4db8e8715b6d833a26f5b11/guide?start=1614394800&end=1614481200
[guide.json.txt](https://github.com/rbuehlma/pvr.zattoo/files/6054737/guide.json.txt)

regarding when using enhanced EPG service, it seems nothing was working, however i haven't tested more than ~50-100 entries 

clearing the kodi EPG data, yes it goes back to working "fine"

thank you!

**Comment by rbuehlma** [comment]
It seems the EPG database for tv.salt.ch is separated from the on of Zattoo. This means that the program IDs are different. This makes it near to impossible for my enhanced EPG service to fetch the detailed EPG information for all the reseller.

For Kodi, its not possible do fetch that information from Zattoo/Salt directly since that would cause too many requests. I therefore fear the only option is not to use the enhanced EPG service if salt.tv is used.

**Comment by oxyrev** [comment]
sure duplicating all requests would be crazy, thanks for your help, I'll use it this way now,  (anyway, why in the hell zattoo thought it was a good idea to waste time in differentiating the ids for the different provider  would be great to know ahah)
