### ISSUE TITLE
No movie abstracts in EPG (19.7.4-Matrix)

### ISSUE THREAD

**Issue by madsci** [rbuehlma/pvr.zattoo#120]
Hi rbuehlma

It looks like you have disabled the enhanced EPG service in the recent version, which is fine as the EPG works with Zattoo as EPG provider (loading time acceptable, replay working, etc).

However, since the change I miss abstracts in movies. There is only the title and the genre displayed but the abstract section is empty. Interestingly, some information such as episode information of a series is available (even same channel). In official Zattoo App I see the abstracts of movies.

If you need log file, I could provide it on the evening.

Thank you for "digging" into this.

Regards
David

**Comment by rbuehlma** [comment]
It might take some time (few hours) until all the data is loaded but then it should look like this:

![2021-03-05_11-01](https://user-images.githubusercontent.com/20914776/110099888-1bd43c80-7da2-11eb-929f-1fe4d8d4a613.png)

Could you provide a screenshot where I see the affected program including its channel and also a debug log?

**Comment by madsci** [comment]
Thank you for your quick reply. Yesterday the EPG looked complete as on the example above. Are all details from a show (e.g. 'nano') loaded simulateneously or are certain details such as "Description" fetched later?

Anyway, I will double check this evening and send requested log files and channel info.

**Comment by rbuehlma** [comment]
Details like the description, season and episode are loaded later. The addon will start from the current shows and then fetch the details in order of increasing distance of time from the current time. This makes sure that the most current shows will get the details first. It might take some hours until the details for all the shows are fetched if the addon database is currently empty.

**Comment by madsci** [comment]
Thanks, this would explain the seen behavior.
After checking debug log quickly, I noticed the following points:
- Details Thread starts normally and EPG details are fetched
- it seems that not only favorite channels but all zattoo-wide available channels are scanned. Starting with favorites would speed up the process
- it also seems that scanning starts when epg is available, which was last Saturday. Starting with "now" would also speed up. 
- Many epg errors and refetch several times the failing items.

Here is the log:
[kodi.log.tar.gz](https://github.com/rbuehlma/pvr.zattoo/files/6093534/kodi.log.tar.gz)

EPG overview with missing details
![20210305_192325](https://user-images.githubusercontent.com/2619081/110177540-6b981f80-7e05-11eb-9cfa-0015b244297f.jpg)

Same here. Example from above:
![20210305_192414](https://user-images.githubusercontent.com/2619081/110177618-8e2a3880-7e05-11eb-8eaf-c5f3a50c2073.jpg)

Successfully fetched description (6 days ago, Zattoo prog ID: 210978194):
![20210305_221855](https://user-images.githubusercontent.com/2619081/110177743-b74ac900-7e05-11eb-812f-8e5aaf019261.jpg)

Series with episode title:
![20210305_192354](https://user-images.githubusercontent.com/2619081/110178165-5b347480-7e06-11eb-92c8-5cd3cbc7f520.jpg)

**Comment by rbuehlma** [comment]
19.7.5 solves the error "Unable to deliver state change for tag" by not loading EPG for channels which are not listed (e.g. if only favorites are listed).

The order in which the EPG is loaded is defined by Kodi and not by the addon. Only the details information (description, episode) are managed by favoritesthe addon and there, it starts with the current program.

**Comment by madsci** [comment]
Yes, I confirm. The error messages are gone with 19.7.5. Thanks for the fix.

Details of shows are however still missing. After short time, I noticed that no further details are fetched: "AddOnLog: pvr.zattoo: Loading details for 0 epg entries". This has not changed for at least 20 min.

My new log is here
http://ix.io/2RWG

**Comment by rbuehlma** [comment]
According to the log, all looks fine and all the details have been loaded.

Could you try to clear the EPG cache in Kodi and if that does not work, send me the file .kodi/userdata/addon_data/pvr.zattoo/epg.sqlite

**Comment by rbuehlma** [comment]
I believe I found the issue. It should now be fixed in 19.7.7

**Comment by madsci** [comment]
Cool! Well-done. I confirm that it works as expected in 19.7.7.
Thank you for your quick help.
