### ISSUE TITLE
Add of Nexus branch and related version

### ISSUE THREAD

**Issue by AlwinEsch** [rbuehlma/pvr.zattoo#127]
Since Kodi 20 Nexus has been available for a some months now, it is time to create an associated Nexus branch and release for all addons, for this then "20.0.0-Nexus".

I'm doing this at all addons where I have access, but you would have to make a change to this one.

**Comment by rbuehlma** [comment]
I have create a branch and hopefully did all the required changes. Could you confirm that:

https://github.com/rbuehlma/pvr.zattoo/commit/aa4669b07a45e9cd61cbc38e051aa3f9359f9c24

You now also have write access to this repo.
