### ISSUE TITLE
build plattform

### ISSUE THREAD

**Issue by buhtz** [rbuehlma/pvr.zattoo#13]
I want to use the addon with LibreELEC 8.2.3 and Kodi 17.6 on a Pi2.

Do you think this is compatible?

I don't understand the underlying build system. Can I execute the build instructions on a x64 Debian unstable and just copy the addon file to my PI? Or do I need to build directly on the PI?
I am not sure if I can get a complete build environment there.

**Comment by rbuehlma** [comment]
I only support the Addon for Kodi v18 (current alpha version). See this thread:
https://www.kodinerds.net/index.php/Thread/58635-PVR-Addon-f%C3%BCr-Zattoo-und-Reseller/
