### ISSUE TITLE
No EPG information on 1und1

### ISSUE THREAD

**Issue by foobar26** [rbuehlma/pvr.zattoo#133]
Hi!
I have been using the zattoo plugin for 1&1 for years now. But recently (about 4 weeks ago) there is no EPG information displayed. Streaming the channels is still possible but I don't see any program information.
I already tried to use previous versions of the plugin, all with no success.
I'm running version 18.1.23.1 on LibreELEC 9.2.8 (most recent).

Thanks for your help!

Kind regards
Frank

**Comment by foobar26** [comment]
Just had a look at the log file.
There I found this:
```
2021-12-13 20:32:35.245 T:2876646208  NOTICE: EPG thread started
2021-12-13 20:32:36.457 T:2661593920   ERROR: CCurlFile::Open failed with code 4
04 for https://zattoo.buehlmann.net/epg/api/Epg/DE/53d5a95ea90d85ee033016086f118
5f4/br/1639267200/1639699200:

```

Seems like a third party URL is no longer available. Any way to fix this?

**Comment by rbuehlma** [comment]
HI foobar26,
i have decommissioned that service because Kodi 19 and with it a newer version with its own EPG database has been released a long time ago.
You have two options to get the EPG back:

1. Switch to Kodi 19
2. Disable the external EPG service (you will loose some of the EPG information).

**Comment by foobar26** [comment]
Ok thanks for your quick answer. Disabling the external EPG works but the timings are not correct.
I will look into the switch to Kodi 19. Hope that all other addons I'm using are still working then...
