### ISSUE TITLE
SRF1 and SRF2 do not appear in thr chanel list

### ISSUE THREAD

**Issue by renesigi** [rbuehlma/pvr.zattoo#138]
I can't remember the date, but at some day in around September/October 2021, the two Swiss channels SRF1 and SRF2 do not appear anymore in the channel list :-(, nor in all nor in all channels or favorits list or in the program guide. In all other Zattoo Front ends (Browser, Win 10 App, Android on phone or tablet, the mentioned channels appear as expected.
Any idea what the reason could be?

**Comment by rbuehlma** [comment]
The only feature in this addon which causes not all channels to be displayed, is when you enable that only the favorites should be shown in the addon settings.

Kodi itself allows some additional functions like sorting or hiding channels. For this, have a look in the channel manager in the settings of Kodi. If the channel does not show up there, I will need a debug log to get more information.

**Comment by rbuehlma** [comment]
Closing ticket due to no reaction.
