### ISSUE TITLE
Group recordings of same series

### ISSUE THREAD

**Issue by Millencolin** [rbuehlma/pvr.zattoo#139]
The recordings screen is hard to navigate as soon as there are more than a few recordings in the list. It would be great if recordings of the same series could be grouped into a subfolder

Kodi has an option to group items (a toggle in the side menu). When enabled, Kodi uses the directory property passed by `kodi::addon::PVRRecording` and displays recordings in subfolders, e.g all episodes from a tvshow are stored in the same subfolder. Since the addon is currently not setting a folder name when retrieving the recordings, the grouping doesn't work. 

Checking if the pvr records contain the property `tv_series_id` when parsing the json data in [`ZatData::GetRecordings`](https://github.com/rbuehlma/pvr.zattoo/blob/409e13137df431994e220d488566c0d215dfd7d9/src/ZatData.cpp#L1129) and then setting the directory to the name of the title could do the trick.

```
if (Utils::JsonIntOrZero(recording, "tv_series_id")) {
    tag.SetDirectory(tag.GetTitle());
}
```

PS: Instead of using the recording title as folder name you could also retrieve the tv series info by looking up the info in the `recorded_tv_series` object which gets returned as part of the json response. 

Thanks for this nice addon

**Comment by rbuehlma** [comment]
I have implemented your suggestion in 19.7.11.

Thanks for your input.

**Comment by rbuehlma** [comment]
I have added a setting for this feature which is disabled by default. With 19.7.12, this feature needs to be enabled in the settings.

**Comment by ksooo** [comment]
See my other comment. No need for this setting as grouping/ungrouping can already be changed in Kodi itself.
