### ISSUE TITLE
Any way to disable "Put series recordings into directories"

### ISSUE THREAD

**Issue by Arokhaerr** [rbuehlma/pvr.zattoo#142]
Well, the title basically sums it all up.
Starting from version v19.7.11 theres this new feature I'd like to disable because my wife prefers the recordings to show up in chronological order.

**Comment by rbuehlma** [comment]
There is now a new setting in v19.7.12 for this.

**Comment by ksooo** [comment]
There is no need for such a setting in the Addon settings as this can be done in Kodi itself. Open the recording windows’ side blade. There is an option to enable /disable grouping of recordings.

**Comment by rbuehlma** [comment]
Thanks for explanation. I will remove that setting again with the next update.
