### ISSUE TITLE
zattoo crash once a day

### ISSUE THREAD

**Issue by Mannshoch** [rbuehlma/pvr.zattoo#143]
Sometimes we had crashes of Zatto (kodi homescreen appear and pvr addon reload). My girlfriedd detected a week ago that it happens every day at the same time. 16:46 now after the summertime change its daily at 17:46 . That's way more anoying than 16:46.

the log do not show anything on this time.

**Comment by rbuehlma** [comment]
I have never observed that issue and without any further information, there is nothing I could analyze. Beside of that, after the stream has been started, inputstream.adaptive and Kodi are responsible for playing the stream. This addon is not involved any more at that point in time.
