### ISSUE TITLE
Missing on Kodi 19.4.0.70 from Microsoft Store

### ISSUE THREAD

**Issue by tpaniaki** [rbuehlma/pvr.zattoo#144]
I downloaded the latest version on my Xbox One X and the addon doesn't show up in Kodi repo. Is it a known issue?

**Comment by rbuehlma** [comment]
I assume that the Xbox One X uses the Windows repository. There, the current version seems to be available. Also the latest build on Jenkins did not have any errors.

@ksooo do you know what might be the issue here? or how could know it?

**Comment by tpaniaki** [comment]
OK bizarre. Is there a way to install it manually from zip without cmake it (I'm on Linux)?

Edit: I should precise I tried with [windows-x86_64](http://ftp.halifax.rwth-aachen.de/xbmc/addons/matrix/pvr.zattoo+windows-x86_64/pvr.zattoo-19.7.11.zip) but it didn't work. I'll happily  debug that if needed.

**Comment by rbuehlma** [comment]
I'm not sure if Kodi on Xbox supports any addon repositories or if all the addons are included with the installer. I have no release a new version 19.7.13 of this addon. If the addons are fetched from a repository, you can check if that version is now available.

**Comment by tpaniaki** [comment]
Thank you for the follow-up. The addon is currently still missing. All PVR clients but yours are available on the console - as if it's been somehow censored or a component of the addon not compatible with the system. I'll keep you posted on the next Kodi release.

**Comment by rbuehlma** [comment]
Mh, ok, since I do not know who to contact, could you create a bug report in the Kodi repository? Then the relevan persons will probably get to it.
