### ISSUE TITLE
no audio with iptv merge

### ISSUE THREAD

**Issue by irontes** [rbuehlma/pvr.zattoo#149]
Hi, I have Libreelec (the lastest release) installed  with PVR Simple Client where I have merged Samsung TV Plus with it and  have also installed Zattoo PVR .
When I have noticed that when I switch from a Samsung channel to a Zattoo channel I lose audio in the video on the first attempt however, if I stop the video, or just change the channel to another Zattoo channel the audio returns again.  This happens only with Zattoo and not with Teleboy.  FYI, this happens on all my devices (Kodi in Windows 10, Kodi in Andriod, CoreElec and LibreElec)
Do you know why this is happening?  Do you have any suggestions for a FIX?

**Comment by rbuehlma** [comment]
No I do not know this issue. Since the stream handling is not done by this addon but by Kodi and inputstream.adaptive, I suggest to open a bug report against Kodi itself and also include a debug log showing the issue.

**Comment by irontes** [comment]
you right is a bug in inputstream.adaptive if uncheck the "play inputstream HLS" in the "merged addon" the issue with audio disappear.
Thank you
