### ISSUE TITLE
Please provide the addon 2.3.0 via the official Kodi repository with the binaries.

### ISSUE THREAD

**Issue by rainman74** [rbuehlma/pvr.zattoo#153]
Please provide the addon **2.3.0** via the official Kodi repository with the binaries.

http://mirrors.kodi.tv/addons/nexus/pvr.zattoo+android-armv7/
http://mirrors.kodi.tv/addons/nexus/pvr.zattoo+android-aarch64/
http://mirrors.kodi.tv/addons/nexus/pvr.zattoo+windows-i686/
http://mirrors.kodi.tv/addons/nexus/pvr.zattoo+windows-x86_64/
http://mirrors.kodi.tv/addons/nexus/pvr.zattoo+osx-x86_64/

The latest version there is: pvr.zattoo-**20.2.1**.zip

**Comment by rbuehlma** [comment]
I believe its the same cause as this ticket:

https://github.com/xbmc/xbmc/issues/21632

Unfortunately, noone from the Kodi team was able to help yet.

**Comment by rbuehlma** [comment]
This is now solved. version 2.3.0 should now be in the repository.
