### ISSUE TITLE
Error with  19.7.16-Matrix

### ISSUE THREAD

**Issue by p0nti** [rbuehlma/pvr.zattoo#155]
getting the following with 19.7.16-Matrix

` ERROR <general>: AddOnLog: pvr.zattoo: EPG-DB: Failed to get info from db using where part.`

**Comment by rbuehlma** [comment]
Please provide a complete debug log and the file .kodi/userdata/addon_data/pvr.zattoo/epg.sqlite

**Comment by rbuehlma** [comment]
Closing issue due to no feedback. Feel free to reopen the issue if required.
