### ISSUE TITLE
No video, only sound on macOS Monterey Kodi 19

### ISSUE THREAD

**Issue by Fischmuetze** [rbuehlma/pvr.zattoo#156]
I'm using the per client on several Macs ... all with the latest version of macOS Monterey 12.6.1.
The pvr Zattoo client works well on all Intel-Macs but on the only Mac with Apple silicon Apple M1 Plus I got on the the sound but no video. I repeated ist again with a fresh installation without an success.

**Comment by rbuehlma** [comment]
Unfortunately, there is not much I can do about this. To play the stream, this addon uses a second addon called inputstream.adaptive. That addon works together with Kodi to play the stream. I therefore suggest to open an issue against Kodi directly. They will be able to sort out wether its an inputstream.adaptive issue or one directly in Kodi. Make sure to also attach a debug log when creating the ticket.

**Comment by Fischmuetze** [comment]
Hi,
Thank you … but I guess the reason of the issue could be depending from the version of the dependency libraries.

I installed wait.tv which have (by names) the same dependencies but with other version requirements .. and wait.tv per is running totally smooth on the same system.




Cheers
Steffen

**Comment by rbuehlma** [comment]
Which dependency are you referring to here? Unfortunately, I cannot find any PVR addon called "wait.tv" and therefore cannot have a look at it. Does it play DASH streams and is it using inputstream.adaptive?

**Comment by Fischmuetze** [comment]
The pvr client called waipu.tv (autocorrection makes wrong things) - see the screenshot that I sent

**Comment by rbuehlma** [comment]
I can't see any screenshot attached.

The only dependency related to playing the video/audio stream of this addon is inpustream.adaptive. There, only a minimal version is defined and the actually used version is much newer.

I do not see any option to influence the video and audio playback from this addon.

**Comment by rbuehlma** [comment]
Closing this issue due to missing feedback.
