### ISSUE TITLE
plugin keeps crashing

### ISSUE THREAD

**Issue by damnms** [rbuehlma/pvr.zattoo#158]
Hi, first of: thanks for the plugin.

Unfortunately it keeps crashing all 1-2h.
In the log i only see: 
2023-01-10 21:50:10.485 T:3753     info <general>: PVR Manager: Starting cleanup of cached images.
2023-01-10 21:50:11.653 T:3753     info <general>: PVR Manager: Cleaned up 5 cached images.
2023-01-10 22:19:44.563 T:3883     info <general>: CVideoPlayerAudio::Process - stream stalled
- then kodi crashes respectively needs a restart because it does not respond to any remote input

**Comment by rbuehlma** [comment]
Unfortunately, there is no usable information in this log. Please provide a complete debug log.

**Comment by rbuehlma** [comment]
I have created an issue against Kodi: https://github.com/xbmc/xbmc/issues/22495

**Comment by rbuehlma** [comment]
This should be fixed with 20.3.3

**Comment by damnms** [comment]
where can i download this version? i only have old versions in the official repositories.

**Comment by rbuehlma** [comment]
You did not provide any information on which environment you are using Kodi. In general, the creator of your Kodi distribution should also provide the addons and update them if required.
