### ISSUE TITLE
Cache fills up all the disk space after some time.

### ISSUE THREAD

**Issue by goggle** [rbuehlma/pvr.zattoo#16]
I'm using pvr.zattoo on the LibreELEC test builds for the raspberry pi 2/3. I've noticed that after some time (maybe after 2-3 months), the cache data that pvr.zattoo automatically produces gets really big (11.5 GB in my case) and is never cleared. This data resides in `~/.kodi/userdata/addon_data/pvr.zattoo/cache`.

Is this an issue of this PVR or should Kodi take care of this? Or is there even an option to prevent letting the cache get that big?

**Comment by rbuehlma** [comment]
No, thats not normal and also not the case for me. In my case, the cache is less than 100 MB.

Did your system run these 2-3 months without a reboot? Are some of the files deleted upon reboot? How many recordings do you have about?

Could you provide the output of ls -lahtr of the cache directory and some of the oldest files? And could you also provide a debug log of the system after it has been running at least for 2 hours?

**Comment by rbuehlma** [comment]
Oh I think I found the error: your account does not support recordings, right? If yes, I do not been the above.

**Comment by goggle** [comment]
Unfortunately I cannot give you the the content fo the cache directory, I've already manually deleted it.
My system was updated and rebooted regularly in these 2-3 months.

You're right, my account does not support recordings. So, you've found the error? What was it? If necessary, I can try to produce such a debug log.

**Comment by rbuehlma** [comment]
Yes, in this case its clear: The cache is cleaned upon loading recordings which never happens in your case :) I will fix this.

**Comment by goggle** [comment]
Thank you verby much for your effort.
