### ISSUE TITLE
download location for builds

### ISSUE THREAD

**Issue by damnms** [rbuehlma/pvr.zattoo#161]
Hello, looking for 20.3.3 for aarch64, but i find no repository that ships that.
I have a odroid n2 running coreelec, unfortunately in the official repo this plugin is quiet old and constantly crashes

#1  0xf32af374 in ?? () from /usr/lib/libc.so.6
#2  0xf32bb490 in ?? () from /usr/lib/libc.so.6
#3  0xf32bb57c in ?? () from /usr/lib/libc.so.6
#4  0xf38b3aee in ?? () from /usr/lib/libGLESv2.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 4 (Thread 0xe04ff2c0 (LWP 4035)):
#0  0xf32b5b60 in pthread_mutex_lock () from /usr/lib/libc.so.6
#1  0xf4f17bc4 in ?? () from /usr/lib/libsqlite3.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 3 (Thread 0xe7cf92c0 (LWP 4006)):
#0  0xf32af230 in ?? () from /usr/lib/libc.so.6
#1  0xf32af374 in ?? () from /usr/lib/libc.so.6
#2  0xf32bb490 in ?? () from /usr/lib/libc.so.6
#3  0xf32bb57c in ?? () from /usr/lib/libc.so.6
#4  0xf38b3aee in ?? () from /usr/lib/libGLESv2.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

```
Thread 2 (Thread 0xe74f82c0 (LWP 4007)):
#0  0xf331d85c in ioctl () from /usr/lib/libc.so.6
#1  0xf35ca252 in ?? () from /usr/lib/libGLESv2.so
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 1 (Thread 0xe3e582c0 (LWP 4036)):
#0  0xd7053be4 in ?? () from /storage/.kodi/addons/pvr.zattoo/pvr.zattoo.so.20.3.1
#1  0xd706062c in ?? () from /storage/.kodi/addons/pvr.zattoo/pvr.zattoo.so.20.3.1
#2  0x010bb3cc in ?? ()
#3  0x00d2dd40 in PVR::CPVRClient::GetAddonNameStringProperties() ()
#4  0x00d3ea7c in PVR::CPVRClient::SetConnectionState(PVR_CONNECTION_STATE) ()
#5  0x00d4d9a8 in ?? ()
#6  0x0109c978 in ?? ()
#7  0x00d45b78 in PVR::CPVRClient::cb_connection_state_change(void*, char const*, PVR_CONNECTION_STATE, char const*) ()
#8  0xd705c7fc in ?? () from /storage/.kodi/addons/pvr.zattoo/pvr.zattoo.so.20.3.1
#9  0xd705cb3c in ADDON_Create () from /storage/.kodi/addons/pvr.zattoo/pvr.zattoo.so.20.3.1
#10 0x00a99570 in ADDON::CAddonDll::Create(KODI_ADDON_INSTANCE_STRUCT*) ()
#11 0x00a999f8 in ADDON::CAddonDll::CreateInstance(KODI_ADDON_INSTANCE_STRUCT*) ()
#12 0x00a99dec in ADDON::IAddonInstanceHandler::CreateInstance() ()
#13 0x00d3e808 in PVR::CPVRClient::Create() ()
#14 0x00d5c2e4 in PVR::CPVRClients::UpdateClients(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int) ()
#15 0x00d730f4 in ?? ()
#16 0x007d85b0 in CJobWorker::Process() ()
#17 0x00853aa0 in CThread::Action() ()
#18 0x010a5580 in ?? ()
#19 0x00851690 in ?? ()
#20 0xf311d920 in ?? () from /usr/lib/libstdc++.so.6
#21 0xf32b2bdc in ?? () from /usr/lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

```

guess thats fixed in the latest version but thats not available somehow ... at least for coreelec. or i am blind

**Comment by rbuehlma** [comment]
You will either have to build the addon on your own or ask coreelec to update their repository.

**Comment by damnms** [comment]
https://discourse.coreelec.org/t/please-update-zattoo-pvr-breaks-nexus/20379
