### ISSUE TITLE
Wrong Username and Password should Prompt a dialog and allow to change

### ISSUE THREAD

**Issue by Mannshoch** [rbuehlma/pvr.zattoo#162]
The Zattoo username got changed. Kodi worked some days. But after a reboot PVR didnot show anything. In such a case Please show a single tile in Zatto with name "Login Error" after tick it, the addon should request for checking username and password.

**Comment by rbuehlma** [comment]
You are right, the error in case the login fails was missing. With 20.3.4, there now is a popup in case of invalid username or password.

![image](https://user-images.githubusercontent.com/20914776/216815227-793b4a83-8d57-4fb7-839b-20569952dd4c.png)

**Comment by Mannshoch** [comment]
How long would this popup appear until it vanish?

**Comment by rbuehlma** [comment]
I don't know it exactly but only for a few seconds. This is not controlled by the addon but by Kodi itself.
