### ISSUE TITLE
Zattoo not displaying my recordings for channel recently removed from available list by Zattoo

### ISSUE THREAD

**Issue by Mike-KL** [rbuehlma/pvr.zattoo#165]
Zattoo recently removed (within the last week) BBC ONE HD from their list of available channels.

I used BBC ONE HD channel as my base for both setting recording timers and then subsequently viewing BBC ONE recordings.

Because this particular channel has been removed from channels listing, the Kodi pvr.zatto addon appears to be confused and cannot find any of my existing BBC ONE recordings; even though they are still fully available within my Zatto stored recordings on web.
(Thankfully I can access them and watch them as usual utilising PC web brower for example)

Following is a short extract from the kodi.log, indicating pvr.zattoo error that occurs..

` 11:55:33.003 T:16248   error <general>: AddOnLog: pvr.zattoo: Open URL failed with -2.
	Line  588: 2023-02-17 11:55:33.003 T:16248   error <general>: AddOnLog: pvr.zattoo: Failed to load details for recordings.
	Line  589: 2023-02-17 11:55:33.051 T:16248   error <general>: CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x27f783d4730) Failed: Stream error in the HTTP/2 framing layer(92)
	Line  590: 2023-02-17 11:55:33.051 T:16248   error <general>: CCurlFile::XFILE::CCurlFile::Open - <https://zattoo.com/zapi/v2/cached/program/power_details/52c978ab894d908c27b19d90076350ad?complete=True&program_ids=237147056,237055115,236967727,236967721,236838068,236739539,236608757,236512111,236440805,236358083,236358077,236358115,236357185,236331267,236331265,236224475,236224387,236202754,236202748,236202785,236236040,235208584,235208547,235208632,235208626,235209440,235209337,235122490,234811751,234808844,234461719,234589063,234808851,234809570,234479925,233913581,233077205,232568898,232500766,231937781,231899279,231826283,231914972,231271658,231243127,231242811,231264833,230596019,230558637,229935378,230285605,229923189,229258346,229256557,229810779,229260728,228581988,229444468,228558042,227926640,227891889,227232423,227232423,227227267,226559136,227039297,224532592,223997618,223942806,223217349,222652783,222644828,221876141,221881494,221552313,220645204,220637695,219308306,219308432,219300673,219308252,219210028,219272017,218659997,218660056,218659970,218561751,218002746,217945730,217945757,217938765,217323130,217252228,217276805,217256660,217281511,217252610,217251750,216630515,216696930> Failed with code 0:
	Line  592: 2023-02-17 11:55:33.052 T:16248   error <general>: AddOnLog: pvr.zattoo: Open URL failed with -2.
	Line  593: 2023-02-17 11:55:33.052 T:16248   error <general>: AddOnLog: pvr.zattoo: Failed to load details for recordings.
	Line  594: 2023-02-17 11:55:33.092 T:16248   error <general>: CCurlFile::CReadState::XFILE::CCurlFile::CReadState::FillBuffer - (0x27f783d31f0) Failed: Stream error in the HTTP/2 framing layer(92)
	Line  595: 2023-02-17 11:55:33.092 T:16248   error <general>: CCurlFile::XFILE::CCurlFile::Open - <https://zattoo.com/zapi/v2/cached/program/power_details/52c978ab894d908c27b19d90076350ad?complete=True&program_ids=216575467,216696967,216573013,217639488,216655741,216697012,216575301,216573190,215895757,215895806,215895839,216528294,215318582,216251994,215204774,216366031,215204767,215312777,215223169,214567287,214612681,214610514,214609519,215109895,214628523,213900112,213835653,213836022,213836016,213835744,213835860,214185403,213236260,213154499,213150298,213150402,213281790,212580746,212591818,210406342,209865227,209090381,207742637,207191769,207192023,207082106,207082083,207082060,207078375,206700344,206394208,206273529,206339908> Failed with code 0:
	Line  597: 2023-02-17 11:55:33.092 T:16248   error <general>: AddOnLog: pvr.zattoo: Open URL failed with -2.
	Line  598: 2023-02-17 11:55:33.092 T:16248   error <general>: AddOnLog: pvr.zattoo: Failed to load details for recordings.
	Line  600: 2023-02-17 11:55:33.128 T:16248   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 282723098
	Line  601: 2023-02-17 11:55:33.128 T:16248   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 282412956
	Line  602: 2023-02-17 11:55:33.129 T:16248   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 280313736
	Line  603: 2023-02-17 11:55:33.129 T:16248   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 280315748
	Line  604: 2023-02-17 11:55:33.129 T:16248   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 280319655`

This Issue is consistent and occurs with pvr.zatto on rpi4 with Libreelec Matrix and Windows PC with Matrix and Nexus versions of pvr.zattoo

Rpi4 Libreelec Matrix - pvr.zattoo v19.7.16.1 installed
WIN Kodi Matrix - pvr.zattoo v19.7.16 installed
WIN Kodi Nexus - pvr.zattoo v20.3.4 installed

PLEASE NOTE: There is still available an alternative BBC ONE HD channel, named BBC ONE LONDON HD, which I have now switched too and will use as replacement favourite channel for BBC ONE from now on and moving forward etc.

For general information BBC ONE was also removed from my favourite channels both in pvr.zattoo and via web browser with Zattoo on the web providing no warning and/or attempt to advise user that a favourite channel from user list had been removed and would user wish (for example) to select and use any available alternative. All BBC ONE based recording timers that were set are also now missing for original BBC ONE channel.

**Comment by rbuehlma** [comment]
Could you try if this new version works for you https://jenkins.kodi.tv/blue/organizations/jenkins/rbuehlma%2Fpvr.zattoo/detail/bugfix%2Fsupport_recordings_without_channel/1/artifacts

Its for Kodi Nexus.

**Comment by Mike-KL** [comment]
Thank you for quick response with a new version to see if it fixes issue. I quickly updated pvr.zatto (Win Kodi Nexus) tested and the update does not appear to improve situation although there are now NO "CCurlFile" error messages. Only error messages for each recording that cannot be found.

Extracts from kodi.log

`
2023-02-18 12:57:14.298 T:12672    info <general>: AddOnLog: pvr.zattoo: EPG-DB: Current version: 3
2023-02-18 12:57:14.411 T:12672    info <general>: AddOnLog: pvr.zattoo: REC-DB: Current version: 1
2023-02-18 12:57:14.412 T:12672    info <general>: AddOnLog: pvr.zattoo: PARAMS-DB: Current version: 1
2023-02-18 12:57:14.412 T:12672    info <general>: AddOnLog: pvr.zattoo: Using useragent: Kodi/20.0.0 pvr.zattoo/20.3.4
2023-02-18 12:57:14.413 T:12672    info <general>: PVR Manager: Starting
2023-02-18 12:57:15.188 T:10904    info <general>: AddOnLog: pvr.zattoo: Current country code: CH
2023-02-18 12:57:15.188 T:10904    info <general>: AddOnLog: pvr.zattoo: Service region country: CH
2023-02-18 12:57:15.188 T:10904    info <general>: AddOnLog: pvr.zattoo: Recall are enabled
2023-02-18 12:57:15.188 T:10904    info <general>: AddOnLog: pvr.zattoo: Recordings are enabled
2023-02-18 12:57:15.188 T:10904    info <general>: AddOnLog: pvr.zattoo: Stream type: dash

2023-02-18 12:57:16.722 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 282412956
2023-02-18 12:57:16.738 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 280313736
2023-02-18 12:57:16.739 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 280315748
2023-02-18 12:57:16.741 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 280319655
2023-02-18 12:57:16.742 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 280319647
2023-02-18 12:57:16.743 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 280319175
2023-02-18 12:57:16.744 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 280310992
2023-02-18 12:57:16.745 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 279669293
2023-02-18 12:57:16.746 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 279669290
2023-02-18 12:57:16.746 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 279687494
2023-02-18 12:57:16.746 T:19320   error <general>: AddOnLog: pvr.zattoo: Channel bbc-one not found for recording: 279687492
`

Unfortunately I cant observe a way to link any of kodi.log recording references with web pages links for a stored recording that plays back ok?

e.g. on webpage an example recording is provided with following URL
https://zattoo.com/series/bbc-one/173299/15?recording=506877790

**Comment by rbuehlma** [comment]
Here we go with the next try:

https://jenkins.kodi.tv/blue/organizations/jenkins/rbuehlma%2Fpvr.zattoo/detail/bugfix%2Fsupport_recordings_without_channel/2/artifacts/

**Comment by Mike-KL** [comment]
Latest test version has fixed issue 👍 

All Zattoo errors in kodi.log are now gone and more importantly all bbc-one recordings are now appearing correctly in overall recordings listing and can be selected for playback.  Following is particular screen grab example of BBC ONE HD Frozen Planet II series recordings. 👍 
 
![zatto_bbc-one_recordings](https://user-images.githubusercontent.com/16574667/219901271-c5f73403-4083-4834-bce8-a6d6d742fc25.JPG)

Thanks for quick review and resolution of this issue.

**Comment by rbuehlma** [comment]
Thanks for the feedback. This is now fixed in 20.3.5
