### ISSUE TITLE
kodi Leia and italian channels

### ISSUE THREAD

**Issue by ulissesss** [rbuehlma/pvr.zattoo#168]
Hi, there is chance to watch the italian channels on Leia or those channels are affected of DRM?
I tried the last version for Leia and is not updated.

**Comment by rbuehlma** [comment]
The last release of Kodi Leia is more than two years old. Since then, two major releases of Kodi have been made. Sorry, there will be no more updates of this addon and Kodi Leia (in fact not even for Kodi Matrix since Nexus has been released more than a month ago.)
