### ISSUE TITLE
dash-widevine doesn't work on recordings

### ISSUE THREAD

**Issue by p0nti** [rbuehlma/pvr.zattoo#174]
Hello,

Setting dash-widevine for certain channels of the RTL group works fine (previously wouldn't play anymore when using dash),
however this does not seem to work for recordings, is there any workaround for this?

Thanks,

**Comment by rbuehlma** [comment]
No unfortunately, there is no workaround. The recordings are only available in HD which does not work on Linux for RTL channels any more. Nothing I can do here. I expect they don't work with the browser on Linux either.

**Comment by rnwgnr** [comment]
We are using the Zattoo PVR plugin with "1&1 TV" and encounter the same problem with the playback of RTL group recordings.

When visiting the 1und1.tv website with Firefox on Linux (eg Firefox 113.0.2 on Arch Linux) the recordings will played in SD mode once you activate the DRM feature in Firefox.

**Comment by rbuehlma** [comment]
I just tried it using Firefox having widevine enabled. The video remains black while the audio is working when watching a recording from RTL

**Comment by rnwgnr** [comment]
This is strange,  what's different on your setup than on mine? :thinking: 
All i needed to do was enable "Play DRM-controlled content" in settings which apparently pulls in Widevine.
![image](https://github.com/rbuehlma/pvr.zattoo/assets/10488791/6ab532f0-84a2-486c-8573-4f3d694d2096)

the content is SD only, but at least it plays: 
![image](https://github.com/rbuehlma/pvr.zattoo/assets/10488791/6e2741ed-d350-48de-a17b-6f5b9c134472)

**Comment by rbuehlma** [comment]
May be 1&1 uses some different encryption settings for recordings since it is a German provider. I'm living in Switzerland.
