### ISSUE TITLE
"Playback failed"

### ISSUE THREAD

**Issue by de-echte-kaasboer** [rbuehlma/pvr.zattoo#177]
Playback fails on several channels, I'll try and attach the kodi.log. You can find the failed attempt starting at 18:34:58.

I hope this is the log format you need.

cu,
kaasboer

[kodi.log](https://github.com/rbuehlma/pvr.zattoo/files/11772475/kodi.log)

**Comment by rbuehlma** [comment]
Try to change the stream type in the settings of the addon to dash widevine. This should help.

**Comment by de-echte-kaasboer** [comment]
I tried all stream types (dash, dash_widevine, hls): no difference, unfortunately. :-/

**Comment by rbuehlma** [comment]
Are you using some kind of VPN? And could you attach the same log with widevine enabled?

**Comment by hawkeyexp** [comment]
I have the same issue with 20.3.8.1 - logs attached but a hint:
free channels like ard zdf etc. are working - only commercial channels like rtl pro7 kabel1 are not working which needs drm.
with 20.3.7.1 it works only the login errors are sucking during startup some times.
[kodi.log](https://github.com/rbuehlma/pvr.zattoo/files/11779574/kodi.log)

**Comment by rbuehlma** [comment]
Could one of you try with this versions if it fixes your issue?

https://jenkins.kodi.tv/blue/organizations/jenkins/rbuehlma%2Fpvr.zattoo/detail/fix_sd_streams/1/artifacts

**Comment by de-echte-kaasboer** [comment]
No VPN here, now taking a look at the Jenkins-URL.

cu,
kaasboer

**Comment by de-echte-kaasboer** [comment]
For the vero 4k+ this one is correct?

https://jenkins.kodi.tv/job/rbuehlma/job/pvr.zattoo/job/PR-178/1/artifact/cmake/addons/build/zips/pvr.zattoo+android-aarch64/pvr.zattoo-20.3.9.zip

Installing fails with following error message:

error <general>: CAddonInfoBuilder::ParseXML: addon.xml from 'pvr.zattoo' for binary type 'kodi.pvrclient' doesn't contain library and addon becomes ignored

Thank you for your effort.

cu,
kaasboer

**Comment by rbuehlma** [comment]
I don't know vero and therefore can't tell you if this is correct.

Jenkins does only build the addon for platforms supported officially by Kodi. I'm not sure if vero is one of these.

**Comment by de-echte-kaasboer** [comment]
Hi,

afaik vero/osmc is based on Debian and the platform is aarch64. So Jenkins has no matching binary. This leaves two alternatives for me: testing the Windows binary or trying to build the addon on the vero 4k.

cu,
kaasboer

**Comment by de-echte-kaasboer** [comment]
Hi,

SUCCESS! :)

I built the addon from the fix_sd_streams branch, installed "inputstream helper" as new dependancy and the fresh pvr.zattoo addon. It now plays all channels.

What's missing now is the EPG, there are no infos shown.

Thank you!

cu,
kaasboer

**Comment by rbuehlma** [comment]
Thanks for testing, The EPG issue has definitly nothing to do with this change. I have therefore created release 20.3.9.

If the EPG issue persists, please try to clear the EPG caches and if that does not help. Open a new issue.
