### ISSUE TITLE
Kodi crashing when stream within zattoo-addon is started

### ISSUE THREAD

**Issue by HYauser** [rbuehlma/pvr.zattoo#180]
Hi!
I've been using the Zattoo addon on android media player (orbsmart) for ages.
Recently, Kodi has crashed when starting a channel (regardless of whether it is from an overview or individually).
Tried all app settings. Zattoo app (standalone) works fine.
Anyone an idea?
[kodi.old.absturz durch zattoo-Senderaufruf.log](https://github.com/rbuehlma/pvr.zattoo/files/11895280/kodi.old.absturz.durch.zattoo-Senderaufruf.log)

(Zattoo add-on v. 20.3.10, Kodi Nexus, Android 9)

**Comment by rbuehlma** [comment]
According to your log, you are using Kodi 20.0. Please Upgrade to Kodi 20.1. This might help with your issue.

if not, please check if your system generates a crash log for Kodi.

**Comment by HYauser** [comment]
Thanks for the quick response. I managed to update to v.20.1. but it didn't change the issue. Where could I find the crash.log? I guess there must be one because after two tries I get the warning "Kodi wird wiederholt beendet" - (kodi is repeatedly terminated)

**Comment by rbuehlma** [comment]
Unfortunately, I don't run Kodi on any Android devices and therefore don't know if there is such a crash log containing the required stack traces.

You may try to completely uninstall the addon including its user data and reinstall it again. Since no other users are complaining, I suspect its something with your setup or stored data.

**Comment by HYauser** [comment]
is there a way to get an earlier version of the addon? the repository only offers the latest version.

**Comment by rbuehlma** [comment]
I'm not aware that any older versions are provided somewhere. To only option I see is to build the add-on on your own but there again I do not know how this is done for Android.

**Comment by HYauser** [comment]
Then I'm lost. Reinstalling didn't change anything. Ok, thank you very much for your help nevertheless!

**Comment by rbuehlma** [comment]
You can try to ask at kodinerds.net, there are more people who might be able to help.

**Comment by xpsychomaxx** [comment]
This is [pvr.zattoo-20.3.6.zip](https://github.com/rbuehlma/pvr.zattoo/files/11923795/pvr.zattoo-20.3.6.zip)

You can try whether the addon or your setup causes the issue.
Good Luck.

**Comment by rbuehlma** [comment]
Closing ticket due to inactivity.
