### ISSUE TITLE
Performance Issue on Channel playback

### ISSUE THREAD

**Issue by codingPF** [rbuehlma/pvr.zattoo#182]
Hi there,

i did update my liberelec 10 to 11 on arrival of version 11.0.1 in March. I had to role back due to stability issues - freeze screen on channel switch. I thought this would be related to update procedure rather than clean install.

I gave it a new try a couple of days ago using new SD and clean install. After installation I got error message about missing widevine which was a surprise but did not worry and installed latest widevine. 

Running latest version 2.3.10 after widevine install (using DE 1&1 provider) turned out to be very slow. Starting playback of a channel takes ~5 sec loading spinner while the old version 19 starts the stream without noticeable delay. Switching channels takes about the same time which can also be found in the logs.

After some digging and comparing the logs it seems to be related to the latest change (in change logs) about channeling everything through widevine. Downgrading to v20.3.9 showed a huge improvement and reduced delay to ~1 sec. 

All this is probably related to my “old” RP3+ but maybe someone had the same issue.

Therefore my questions:
Did someone see performance drop on v20.3.10?
Is this some Kodi related issue using DRM for unprotected streams?
Is there any chance to review decision in 2.3.10 to remove stream type option?

I can provide logs and more figures in case there is an interest in this topic…

thx

**Comment by rbuehlma** [comment]
20.3.11 now uses dash widevine if the automatically selected quality does not require drm. Hopefully, this solves your issue.

**Comment by codingPF** [comment]
Thanks a lot for your effort put into this!
Just got v20.3.11 pushed to my W10 Kodi 20 portable (test) version.
The situation has change in a way that 1080p channels will work but other channels (e.g. 576p) will try to use widevine which is not installed on this client. All channels are playable on 2.3.9 - there is no "DRM" protection or need.
I did not check on the code but is seems to be that the requires DRM flag needs some more tuning or probably i do not understand the issue…

**Comment by rbuehlma** [comment]
Could you provide a debug log of playing such a change that does not work?

**Comment by codingPF** [comment]
Sure...i did cleanup my w10 test installation as much as possible to avoid any log spam from other addons and remove myuser name from the logs. The log contains startup, play channel, shutdown. Please let me know in case you more information.


[kodi.log](https://github.com/rbuehlma/pvr.zattoo/files/12063591/kodi.log)

**Comment by rbuehlma** [comment]
According to the log, you are trying to play Pro7. This channel is available in HD but requires DRM. Since you are running Kodi on a Windows, the addons assumes that Widevine is available with at least L2. In this case, you should be able to play Pro7 in HD. Now either widevine is not correctly installed or your windows does not support L2. Do you know which is the case?

**Comment by rbuehlma** [comment]
I will probably add a setting which allows to specify the DRM level which may be used (including none). Determine the level base on the OS does not seem to be reliable enough.

**Comment by codingPF** [comment]
> Now either widevine is not correctly installed or your windows does not support L2. Do you know which is the case?

The W10 portable installation is for testing different Kodi versions only. I am pretty sure widevine is not installed. 
One question: why is it working with v2.3.9? Is it automatically downgrading the stream?

**Comment by rbuehlma** [comment]
20.3.12 now allows disabling DRM in the settings completely or setting it to a custom value. This should now solve your issue also on windows.

**Comment by codingPF** [comment]
Thanks a lot for the update in 20.3.12!
I did a quick check and change configuration DRM level to "disable DRM".
This solved the issue for Pro7 and most others channels but there are still some failing (e.g. RTL, RTL2, Toggo, Disney, Nick, Nitro) on DRM (widevine).

I am not sure if i did something wrong on the confugration - therefore please find debug log attached.
[kodi - RTL.log](https://github.com/rbuehlma/pvr.zattoo/files/12083284/kodi.-.RTL.log)

Just double checking - I did install v20.3.6 on the same device and it works also for the mentioned channels  

PS. I can try to compile the code on my own in case it makes your live easier. In this case there would be a need to create new version tags all the time…just an offer

**Comment by rbuehlma** [comment]
Actually there is no need to build it yourself since jenkins builds a package for every change.

Can you provide me the log of this one?

https://jenkins.kodi.tv/blue/organizations/jenkins/rbuehlma%2Fpvr.zattoo/detail/bugfix%2Fdrm_level/1/artifacts/

This does not solve the issue but just adds some log information.

**Comment by rbuehlma** [comment]
This could even fix your issue:

https://jenkins.kodi.tv/blue/organizations/jenkins/rbuehlma%2Fpvr.zattoo/detail/bugfix%2Fdrm_level/2/artifacts

If not, it might not be possible to watch RTL without DRM.

**Comment by codingPF** [comment]
The last fix seems to resolve the issue. I did try 70 channels from 1&1 channel list on W10 without issues. They work in 1080p / 760p and 576p for the once mentioned before (RTL, RTL2, etc). Thats good enough for me.

I will try the package with my RP3 and let you know the outcome (do not expect a difference).

**Comment by rbuehlma** [comment]
Release as 20.3.13

**Comment by codingPF** [comment]
I do not know the reason but the update did not make it to my libreelec 11.0.3  installation. But I will update as soon as it does…
