### ISSUE TITLE
zattoo pvr client fail to load at the start

### ISSUE THREAD

**Issue by numbernumero** [rbuehlma/pvr.zattoo#183]
Hi, I installed Zattoo PVR client (v. 19.7.16.1) on my device (an Intel NUC with LibreELEC 10.0.4) zattoo PVR often does not load channels so I have to restart libreelec several times before loading the channel list. this only happens with the Kodi MATRIX . I did some testing with other versions of kodi (Leia & Nexus) and both LibreELEC (9.2.6 Leia) and LibreELEC (11.0.1 Nexus) works fine.
I sincerely hope that you can solve this problem that plagues MATRIX versions . I also want to thank you for the amazing work you do to keep this addon up to date.

**Comment by rbuehlma** [comment]
The described issue has been fixed in the addon for Kodi 20 (Nexus) which is available since more than 6 months. Therefore there won't be any updates for any older version of the addon from my side.
