### ISSUE TITLE
Include Season/Episode information, when available within episode description.

### ISSUE THREAD

**Issue by Mike-KL** [rbuehlma/pvr.zattoo#187]
Currently pvr.zatto recordings within kodi Nexus provide date/time and short description of each recording in addition to title, but do not include Season/Episode when it is included as an element of detailed description information on Zatto webpage.

Would it be possible to include Season/Episode information in future update where/when its available?

Example in Kodi

![Kodi Emmerdale Episode Details](https://github.com/rbuehlma/pvr.zattoo/assets/16574667/1513e2f2-088d-42b2-b445-afd6467c7d5b)

Example Webbrowser

![Web_Browser Emmerdale Episode Details](https://github.com/rbuehlma/pvr.zattoo/assets/16574667/544af345-57d1-4a87-a4ee-25fead4714ad)

**Comment by rbuehlma** [comment]
Something seems to be wrong in your case. The addon should fetch this information:

![image](https://github.com/rbuehlma/pvr.zattoo/assets/20914776/6d7c96dc-42ec-4ccc-9a08-269f93fac93a)

But it might take a very long time until all the details for every program are fetched.

**Comment by Mike-KL** [comment]
Using latest Kodi Nexus on both Win10 and Rpi4 and results are the same in my case, no season/episode information appears to be fetched/presented in Kodi for any of my personal Zatto programme recordings?  Checking past/current/future programmes contained within EPG, I now notice that Season/Episode information is typically included. (pvr.zatto 20.3.13)

So it appears to be a problem with user specific saved recording information from Zatto and how this is being fetched and then presented in Kodi, that is not including the Season/Episode information.

EPG with Season/Episode information included for specific programme on Tue 1st August

![Kodi EPG Emmerdale Details 1](https://github.com/rbuehlma/pvr.zattoo/assets/16574667/04006a42-89c6-4370-bf10-43769963d557)
![Kodi EPG Emmerdale Details 2](https://github.com/rbuehlma/pvr.zattoo/assets/16574667/69f53e82-545e-4c8b-a6ad-7df40d196847)

PVR Recording with No Season/Episode information for same specific programme on Tue 1st August

![Kodi Recording Emmerdale Details 1](https://github.com/rbuehlma/pvr.zattoo/assets/16574667/898619e3-0da7-4fde-9297-af740d86a034)
![Kodi Recording Emmerdale Details 2](https://github.com/rbuehlma/pvr.zattoo/assets/16574667/6c3d7bc0-be78-48b8-9f98-326df015f49f)

**Comment by rbuehlma** [comment]
Thanks for the additional information. This is now fixed in 20.3.14

**Comment by Mike-KL** [comment]
@rbuehlma thank you very much for very quick fix.
Update release already automatically, installed from kodi repo and tested on Win10 PC ;-)
Thanks again
