### ISSUE TITLE
Load channels

### ISSUE THREAD

**Issue by numbernumero** [rbuehlma/pvr.zattoo#189]
Hi, I know that on the version for Matrix there is no more support and I understand it, unfortunately I am forced to stay with libreelec 10.04 (Matrix) and in this version Zattoo PVR does not always load the channels at the beginning. I noticed, however, that waiting 5 or 10 or even 15 minutes from the start zatto pvr starts again and loads the channels. 
noted that even if with delay Zattoo still loads the channels I made a build of zattoo in which I modified lines 108 and 127 in the file "Session.cpp" replacing "_m_nextLoginAttempt = std::time(0) + 300;_" with "_m_nextLoginAttempt = std::time(0) + 60;_.
Now it works great even if I have to wait 2 or 3 attempts at the end only 2 -3 minutes instead of 15. But I would like to know if these changes can lead to other types of problems or if I can even change from "60" to "30" without causing other types of problems. 
Thank you very much for any answer and for the excellent work you do

**Comment by rbuehlma** [comment]
This functionality should, in case of a failed login, prevent too frequent retries. If the login fails too often (about 3 times) in a certain time frame, the IP will get blocked by Zattoo for some time.
