### ISSUE TITLE
Crash when changing channels

### ISSUE THREAD

**Issue by edenmedia** [rbuehlma/pvr.zattoo#190]
Hi, in Libreelec 11.03 (Kodi Nexus 20.2) Zattoo Pvr often crashes when changing channels. I guess you are already aware of the problem and that the cause is "Inputstream". I sent a report to the Inputstream team but I think that if you would also send a report about the problem since you are an addon developer you would be more considered.

**Comment by rbuehlma** [comment]
I do not observe this issue and therefore also can't report it anywhere.

**Comment by edenmedia** [comment]
Sorry, do you mean that is only me that have problems with zattoo pvr in libreelec?
I did a fresh install of libreelec 11.03 then I installed only Zattoo Pvr.
When changing few channels it will crash and restart by it self.
LOG here: https://paste.kodi.tv/togugibati.kodi
Crash Log here: https://paste.kodi.tv/uzeditiqug.kodi

**Comment by rbuehlma** [comment]
No, I never wrote that you are the only one observing this. But you asked me to report me an issue (which by the way has already been reported here: https://github.com/xbmc/inputstream.adaptive/issues/1362) for an issue which I cannot reproduce and cannot provide any information for it. I also tried to zap through more than 50 channels without any issues.

**Comment by edenmedia** [comment]
I can't reopen the issue maybe only the owner of the repo or a collaborator coud do that
