### ISSUE TITLE
Load channels in Libreelec Nexus

### ISSUE THREAD

**Issue by irontes** [rbuehlma/pvr.zattoo#192]
Hi, I do not understand why close the issues  #190 this problem also afflicts me and many other user
I have the same issue with LE Nexus. 
The problem of the PVR crash with inputstream is known to many users especially in Libreelec Nexus. We hope that the Inputstream Developers will find a solution (https://github.com/xbmc/inputstream.adaptive/issues/1362) otherwise we have to migrate to Android and use the related apps TV Mate, Zattoo etc.

**Comment by rbuehlma** [comment]
Opening a new issue for the same problem again won't help. As you already stated, the error happens in inputstream.adaptive and there, an issue has already been created. There is nothing I can do in this addon.
