### ISSUE TITLE
Channel guide uses strange language 

### ISSUE THREAD

**Issue by olaflischke** [rbuehlma/pvr.zattoo#193]
Channel guide uses strange language for ARD.

**Comment by rbuehlma** [comment]
I don't see anything strange there. Please provide additional information and a screenshot. Writing in German would be fine as well.

**Comment by olaflischke** [comment]
Meanwhile it's happening for all channels:
![PXL_20231023_113032529](https://github.com/rbuehlma/pvr.zattoo/assets/13316482/3ad10f72-0d1e-40a7-83f7-35aeaf26d9fa)

Libreelec 11.0.3
pvr.zatto 20.3.14.1

**Comment by rbuehlma** [comment]
I suspect you need to change the language in your Zattoo account on the Zattoo website.

**Comment by olaflischke** [comment]
Is being set to German.


Von: René Bühlmann ***@***.***>
Gesendet: Montag, 23. Oktober 2023 13:51
An: rbuehlma/pvr.zattoo ***@***.***>
Cc: Olaf Lischke ***@***.***>; Author ***@***.***>
Betreff: Re: [rbuehlma/pvr.zattoo] Channel guide uses strange language (Issue #193)


I suspect you need to change the language in your Zattoo account on the Zattoo website.

**Comment by rbuehlma** [comment]
Unfortunately, in this case I do not know what else could cause this issue. This addon does not set any language when fetching the data. The language set in on the Zattoo page should be used. You can try the following steps:

- Stop Kodi
- Delete the file ~/.kodi/userdata/addon_data/pvr.zattoo/epg.sqlite
- Start Kodi
- Clear the EPG data in Kodi

**Comment by olaflischke** [comment]
For all running across the same effect: Last step (Clear the EPG data in Kodi) fixed it - wasn't aware of that function well hidden in Kodi settings, tried it first before deleting anything on a lower level. Worked.
Seems switching between different PVR Client addons caused the trouble.
