### ISSUE TITLE
Name of channel groups

### ISSUE THREAD

**Issue by martin3000** [rbuehlma/pvr.zattoo#202]
What are the name of the channel groups, how are they constructed and can they be renamend?
It seems if I rename "International" to "Zattoo_International", after the next Kodi start the old name is back.

**Comment by ksooo** [comment]
Not related to the add-on. Go to Kodi settings -> PVR and TV -> find "Sync channel groups with backends", turn it off. Read the explanation for this setting and you will find, that this setting syncs (thus renames) the group to the name it has in the backend.

**Comment by martin3000** [comment]
And the backend is the zattoo addon, yes? So which names are given for the groups? I have so many groups that I do not see the zattoo groups.

**Comment by rbuehlma** [comment]
The group names are received from the Zattoo Website. Its not possible to change their names there as far as I know.

**Comment by martin3000** [comment]
Thank you
