### ISSUE TITLE
Replay doesnt work on all Entries (Ultimate Subscription) 

### ISSUE THREAD

**Issue by artqcid** [rbuehlma/pvr.zattoo#207]
Kodi Omega on Android Box
Zattoo Ultimate Subscription (CH)

I am not able to replay all Entries in the EPG of Zattoo. Some series and Movies show the green circle, others not. Happens on all Channels.
Works on Zatto App and Browser, but not in Kodi Omega.

**Comment by rbuehlma** [comment]
Please provide an exact sample that does not work for you.

Also please provide the file ~/.kodi/userdata/addon_data/pvr.zattoo/epg.sqlite

**Comment by artqcid** [comment]
Ok, I tried to reinstall the zattoo pvr again. Now no replay is working anymore. If I go to a episode in the past then the menu entry to play don't appear anymore. No more green circles on the epg entries. 

I have an android Box and I don't have access to the files on the box

**Comment by rbuehlma** [comment]
This sounds strange. You could try to clear the EPG cache in Kodi and check if that helps.

**Comment by artqcid** [comment]
Works after I clean the cache from the Kodi App in Android Box. Very Strange.
