### ISSUE TITLE
mutex.Unlock() missing in UpdateThread::Process() => https://trac.kodi.tv/ticket/17912

### ISSUE THREAD

**Issue by ksooo** [rbuehlma/pvr.zattoo#21]
https://github.com/rbuehlma/pvr.zattoo/blob/286ce5f8daabb1be399fa2e818292b871cc42c63/src/UpdateThread.cpp#L120

there, an `else` case is missing which unlocks the update thread mutex. This leads (most probably) to the deadlock and the not working epg update described in https://trac.kodi.tv/ticket/17912

**Comment by rbuehlma** [comment]
This is fixed in 18.0.47. Thanks for the analyse.

**Comment by quthla** [comment]
@rbuehlma i just ran into the same issue with teleboy. This fix probably needs to be applied there too
