### ISSUE TITLE
Feature request: skip extratime in replay (kodi omega)

### ISSUE THREAD

**Issue by madsci** [rbuehlma/pvr.zattoo#215]
Hi rbuehlma

Starting with omega, a dream came true. Two important features in replay mode for [me](https://github.com/xbmc/xbmc/issues/16974) have been implemented:
- automatic progressing to adjoining TV programme when time slot has been finished
- stay in past in the epg after pressing stop

Thanks all the involved people for this.

However, one drop of bitterness comes from overtime and thus overlapping programmes. When you start to watch at 8 o'clock for instance the news with a lenght of 30 min, the replay goes until 20:50. Then kodi jumps back to 20:30 to the official start of the adjoining show. After skipping 20 min, the position is in line again.

Would it possible to implement automatic skipping of pretime (it is already done) and extratime, preferably configurable in the options? For Zattoo the extratime is 20 min.
In recordings, the extratime is important due to possible shift while broadcasting.

Thanks for all the effort
David

**Comment by rbuehlma** [comment]
This has been implemented in 21.0.4
