### ISSUE TITLE
Missing option description - skipEnd?

### ISSUE THREAD

**Issue by cpy82** [rbuehlma/pvr.zattoo#219]
LibreELEC (Omega) 12.0.1
pvr.zattoo 21.0.4-Omega
Raspberry Pi 4

I think the description for “skipEnd” is missing here.

![screenshot00003](https://github.com/user-attachments/assets/d51408cc-7612-48c8-9001-820c487029ab)

**Comment by rbuehlma** [comment]
It's already fixed in the code but I did not create a new release yet.
