### ISSUE TITLE
Replay not available

### ISSUE THREAD

**Issue by tpaniaki** [rbuehlma/pvr.zattoo#220]
**Kodi 21.1. Xbox
Addon 21.0.3**

I switched to a premium account (CH) but can't get the replay to work. I cleared all caches and restarted the addon. Possibly solved in 21.0.4?

**Comment by rbuehlma** [comment]
Its not an issue of 21.0.3. Please provide more information. I'm sure you will come up with some that might be helpful to analyze this  ;)

**Comment by tpaniaki** [comment]
Below some log. As you'll notice, Xbox Kodi is currently experiencing python paths initialization failures but I don't see anything of the kind related to Zattoo. However, your log reports some errors, I'll let you investigate.

[Full log.](https://paste.kodi.tv/eloxuraxir)

**Comment by rbuehlma** [comment]
According to the Log, your account does not seem to support recordings or replay:

<general>: AddOnLog: pvr.zattoo: Service region country: CH
2024-10-15 02:19:56.255 T:1572     info <general>: AddOnLog: pvr.zattoo: Recall are disabled
2024-10-15 02:19:56.255 T:1572     info <general>: AddOnLog: pvr.zattoo: Recordings are disabled

Are you able do use replay on their website?

You can try to completely uninstall the addon including user settings and reinstall it again. Not sure if that will help.

**Comment by tpaniaki** [comment]
The official Zattoo app on Xbox grants the replay to my account. So it's not account-related.

I can't uninstall the addon on Xbox but only disable it. Disabling/enabling does not solve the isue.

**Comment by rbuehlma** [comment]
If possible, you can try to delete the folder ~/.kodi/data/userdata/addon_data/pvr.zattoo/ and then restart. Not sure if that will help but I have no other idea.

**Comment by tpaniaki** [comment]
> If possible, you can try to delete the folder ~/.kodi/data/userdata/addon_data/pvr.zattoo/ and then restart. 

This works, danke sehr. 

For others possibly affected: 

1. As FTP has been disabled on Xbox, you need to install ADV (FullTrust).
2. Kodi's root folder is located at Q: Users > UserMgr0 > AppData > Local > Packages.
3. Find a folder starting with XBMC.
4. In that folder, go to Local state >  userdata > addon_data and you'll find pvr.zattoo.
5. Remove that folder. 
6. Restart Kodi and re-enter your Zattoo credentials.
