### ISSUE TITLE
Zattoo videofeed do not start

### ISSUE THREAD

**Issue by Mannshoch** [rbuehlma/pvr.zattoo#26]
Codec are in config.txt

solved -> i had to change from dash to hls

**Comment by rbuehlma** [comment]
To get dash working, you can activate the inputstream.adaptive addon.

**Comment by Mannshoch** [comment]
Could you may add somewhere a description what's the difference between dash and hls?
From your comment I assume that  dash is better?

**Comment by rbuehlma** [comment]
Dash works very well for me. Others prefer HLS
I assume that it depends on the internet stability but feature wise, there is no difference i know of.

**Comment by Mannshoch** [comment]
Could you may add an Internal check to detect which mode is working and set it up?
