### ISSUE TITLE
Skipping of recording doesn't work

### ISSUE THREAD

**Issue by almarusch** [rbuehlma/pvr.zattoo#29]
I'm using pvr.zattoo in the LibreElec Testbuilds for Kodi 18 on a Raspberry Pi
Until 06.11. i used Leia Build #[1030](https://forum.kodi.tv/showthread.php?tid=298461&pid=2787391#pid2787391) Since 07.11. Kodi crashed with activated pvr.zattoo plugin, fall in reboot loop so kodi boots in emergency mode where i deactivated pvr.zattoo. Facing toward strategy i wiped the entire system, started with a fresh LibreELEC install and updated first to Leia build #[1106](https://forum.kodi.tv/showthread.php?tid=298461&pid=2789605#pid2789605). Here is the [KODI_CRASH.log](http://termbin.com/2230). Still facing toward strategy i moved to Leia build #[1108](https://forum.kodi.tv/showthread.php?tid=298461&pid=2790190#pid2790190)
Fortunately the circumstance that let kodi crash with activated pvr.zattoo seems to be gone. Unfortunately during playback of a record i'm now unable to shift forward. The button 'forward' is not available anymore and the corresponding button on the remote doesn't work.

**Comment by ksooo** [comment]
> The button 'forward' is not available anymore and the corresponding button on the remote doesn't work.
 
 pvr.zattoo uses inputstream.adaptive for playback. This is an issue with inputstream.adaptive, not pvr.zattoo. inpustream.adaptive does not implement the "ITimes" interface which (afaik) in Kodi 18 is needed for proper stream navigation. You should open a ticket for inputstream.adaptive (https://github.com/peak3d/inputstream.adaptive/issues).

**Comment by rbuehlma** [comment]
Seeking in streams does work for me. Do you have inputstream.adaptive active and DASH set as stream type in the pvr.zattoo addon?

@ksooo is it possible that hls streams are handled by inputstream.adaptive if it is active and else by Kodi itself?

**Comment by ksooo** [comment]
Don't know, sorry.

**Comment by almarusch** [comment]
@rbuehlma: DASH zattoo stream type is (still) activated by default in the configuration. I didn't touch that parameter.

@ksooo : It seems you are on the right way. The interface icon 'next chapter' doesn't respond properly as button by selecting and activating it with arrow-navigation. Same if I am pressing the 'forward' key on the remote. I was able to skip a certain time window if i'm navigating on the progress bar on the Video Player OSD and use 'right arrow' until the marker reached the selected target time.

But the same time-skipping function works if i'm watching a regular movie or tv show so it seems it isn't too general and reproduceable. What i could imagine is that every PVR plugin on Leia build #[1108](https://forum.kodi.tv/showthread.php?tid=298461&pid=2790190#pid2790190) is unable to handle the skip function. Either it's a issue of Kodi PVR or a issue for inputstream.adaptive (https://github.com/peak3d/inputstream.adaptive/issues). 

Do you have any ideas for further test actions on higher level of debugging info so the partner projects (Kodi / inputstream.adaptive) have enough information for debug?

**Comment by almarusch** [comment]
The issue can be closed. Somehow it's working now. :)
