### ISSUE TITLE
If you use Simple TV Zatto EPG and numbering is not anymore working

### ISSUE THREAD

**Issue by Mannshoch** [rbuehlma/pvr.zattoo#38]
I try to add som channel with "PTV Simple" but after adding them the EPG of zatto disappear, even I only try to add a Radio channel. 

If I try to add a tv Channel, the TV order is not anymore correct. I could set up PTV Simple what ever i want, from that time I add the zatto plugin the Order from PTV Simple not anymore starts from 100 it starts then from 1 and zatto came after this channel. 
I wish it to start zattoo from 1 and PTV Simple from 100

**Comment by rbuehlma** [comment]
I guess you are using the setting "PVR & LiveTV" -> General -> "Use channel numbers from backend"?
The info for this setting states that this option cannot be used together with multiple PVR add-on. If multiple addons are used, the addon cannot define the channel number anymore. Therefore, there is nothing I can do to change this in the addon. You would need to create a feature request against Kodi.

**Comment by Mannshoch** [comment]
Thanks for information. Is there also a solution for the EPG?

**Comment by rbuehlma** [comment]
Try to clear the EPG Cache in the settings and check if the EPG is then loaded again. Else, it's most probably also an issue in Kodi itself.
