### ISSUE TITLE
Set timer GenreType after TransferTimerEntry

### ISSUE THREAD

**Issue by flubshi** [rbuehlma/pvr.zattoo#39]
Hi rbuehlma,

thanks for your great zattoo pvr addon. I'm not a zattoo user, but I used your addon as template/for inspiration while creating an own pvr plugin.

During the review of your source code I noticed at one point that you set the GenreType and GenreSubType after transferring the tag.
I'm not sure if it is relevant, but I would expect PVR->TransferTimerEntry to be called afterwards:
https://github.com/rbuehlma/pvr.zattoo/blob/30868ce353562cc61e7413f36273dfe0911253d3/src/ZatData.cpp#L1216-L1222

**Comment by rbuehlma** [comment]
Thanks for your input. This for sure is an error :) I have fixed it.
