### ISSUE TITLE
Video stream 25fps under Android instead of 50fps under Windows

### ISSUE THREAD

**Issue by trepmag** [rbuehlma/pvr.zattoo#52]
Hello, 

I noticed that the stream under an Android TV output at 25fps instead of 50fps on a windows box. 

With the "zatto box" addon playing the same channel output at 50fps...

**Comment by rbuehlma** [comment]
Could you please provide a complete debug log? Else, its not possible to analyze this issue.

**Comment by trepmag** [comment]
Here is a full log (from kodi start, play a channel to kodi shut down):
[kodi-pvr-zattoo.log](https://github.com/rbuehlma/pvr.zattoo/files/3394207/kodi-pvr-zattoo.log)

**Comment by rbuehlma** [comment]
You are currently using hls as stream type. Try to switch to dash and if that does not help, try dash_widevine as well. For widevine, you will need to prepare Kodi to be able to play widevine, you should find some manuals on how to do this if you search for howtos to setup Netflix with Kodi.

**Comment by trepmag** [comment]
The 3 stream types was tried and each shown an output of 25fps (noticed when hitting 'o' while playing the stream)...

**Comment by rbuehlma** [comment]
According to your debug log, first the 50fps stream gets loaded:

> UpdateFpsDuration fpsRate:50

But the render manager then sets it to 25:

> 2019-07-15 22:49:43.307 T:19307   DEBUG: CRenderManager::Configure - change configuration. 1280x720. display: 1280x720. framerate: 25.00.

I suspect this is not an issue with pvr.zattoo but with Kodi itself or maybe inputstream.adaptive. You can try to open a ticket in the Kodi repo but this is out of control of this addon.

**Comment by trepmag** [comment]
Thanks for you analysis; closing this. Will try to find if I can reproduce this outside of pvr.zattoo...

**Comment by trepmag** [comment]
Hi, found that setting the 'Enable Pre-release Features' option in expert section of the 'InputStream Adaptives' add-on configuration output the stream at 50fps now (and stream quality seems better)...

**Comment by rbuehlma** [comment]
Thanks for the update. Good to know that. Would not have expected this setting to make any difference.
