### ISSUE TITLE
If a Movie already run you only could record it by open the channel

### ISSUE THREAD

**Issue by Mannshoch** [rbuehlma/pvr.zattoo#59]
It's not anymore possible to record by the guide if the movie already run. You have to open channel and click recording there.

**Comment by rbuehlma** [comment]
I cannot reproduce this problem. I could record a program from EPG while it was already live. Sometimes, there is a timing issue where Kodi does not realize that the recording has actually been started. After 5-10 minutes the list of recordings should then be updated.

**Comment by rbuehlma** [comment]
In 18.1.7/19.2.3 updating recordings and timers should now be more reliable.
