### ISSUE TITLE
Improvements / new features

### ISSUE THREAD

**Issue by madsci** [rbuehlma/pvr.zattoo#60]
Hi

I am using your addon daily and it does what it should. 2 improvements would make the experience even better:
- I am using reply over EPG. When pressing "stop" or "back" to return back to EPG, the time/date is reset to now. I would appreciate if it jumps to the just played entry.
- The second is also about reply function. Playing is stopped when the selected broadcast (with some extra time to compensate programm shifts) ends. Would it be possible to continue with the next broadcast? Furthermore, the EPG jumps back to now.

Thank you for considering my imput
David

**Comment by rbuehlma** [comment]
I agree that both points would be an improvement and I would like to see the as well but unfortunately, this it not something I can change in the addon. This would need to be implemented in Kodi itself. You can open a ticket against Kodi. If you do so, please add here the link to that ticket for future reference.

**Comment by madsci** [comment]
I see. Thank you for your promt reply. I have posted the request to KODI repository.
https://github.com/xbmc/xbmc/issues/16974

**Comment by rbuehlma** [comment]
Closing this issue since it needs to be solved in Kodi.
