### ISSUE TITLE
How could I activate Replay in Zatto? (have zattoo premium)

### ISSUE THREAD

**Issue by Mannshoch** [rbuehlma/pvr.zattoo#66]
From #23 I got that this kodi app should allow replay. How could I activate it? 
I tested dash and das/widvine but on my kodi (Libreelec) does only show me TV if I use hsl.

Libreelec 19.1
Zattoo PVR 18.1.4.1

**Comment by rbuehlma** [comment]
Please provide a complete debug log.

Also please try the current version 18.1.9

**Comment by Mannshoch** [comment]
If I download 18.1.9 from https://github.com/rbuehlma/pvr.zattoo/releases Kodi tell me a wrong internal structure.

**Comment by rbuehlma** [comment]
Just downloading the source from github does not work for PVR addons since they need to be build for each environment. I do not know how the addon update process of LE is. You might want to ask this in the LE forum. If you get some information, it would be great if you can post the link here.

The complete debug log could still help.

**Comment by Mannshoch** [comment]
[kodi.zip](https://github.com/rbuehlma/pvr.zattoo/files/3978467/kodi.zip)

**Comment by rbuehlma** [comment]
Ok, there seem to be multiple problems:

- To use DASH, you need to have inputstream.adaptive installed and active (the new version of pvr.zattoo enforces this).
- To use replay, you do not need to use DASH (though it works better with it) but you need to activate replay in your Zattoo account on the page.

I hope this helps.

**Comment by Mannshoch** [comment]
I was not able to install inputstream. 
Now I detected that kodi got an update to 9.2 I now update it. lets check if something work better after this update.

I was not able to found a refreshed Addon for zattoo even if I install kodinerds repository. It seems there is no zattoo addon in it.

I give you feedback if this update to 9.2 is finished.

**Comment by Mannshoch** [comment]
I could Tell you that 9.2 was the solution. In Libreelec 9.2 I'm able to install inputstream.adaptive and now I have the replay TV available. 👍
I still was not able to get an Update for Zattoo PVR. Libreelec ships still the same version.

OT: Could you may Update the Readme.md with Information about Features like Replay-TV and the hint to the inputstream.adaptive that would be helpful.

**Comment by rbuehlma** [comment]
Yeah, updating the readme is probably a good idea. Current versions of pvr.zattoo depend on inputstream.addaptive which will therefore automatically be installed together with pvr.zattoo.
