### ISSUE TITLE
Wrong version of addon in Leia repo

### ISSUE THREAD

**Issue by rbuehlma** [rbuehlma/pvr.zattoo#69]
Somehow a 19.* version got published in the Leia repo for Windows:
http://mirrors.kodi.tv/addons/leia/pvr.zattoo+windows-x86_64/

Other platforms like android do contain the right version:
http://mirrors.kodi.tv/addons/leia/pvr.zattoo+android-armv7/

I therefore assume this was a glitch in the build system.

Building 18.1.11 again did not help:
https://jenkins.kodi.tv/blue/organizations/jenkins/rbuehlma%2Fpvr.zattoo/detail/18.1.11.1-Leia/1/pipeline/18/

**Comment by rbuehlma** [comment]
@ksooo are you able to help here or do you know who might be able to?

**Comment by ksooo** [comment]
Sorry, no. Maybe @Rechi can help.

**Comment by rbuehlma** [comment]
@Rechi can you have a look into this? I made a new release yesterday but the windows version in the Leia repository still contains the version meant for Matrix.

**Comment by rbuehlma** [comment]
Fixed here:
https://github.com/xbmc/xbmc/issues/17394
