### ISSUE TITLE
Since some days: replay and recording do not play on some channels

### ISSUE THREAD

**Issue by Mannshoch** [rbuehlma/pvr.zattoo#70]
Since some days: replay and recording do not play on some channels. No message appear, simply nothing happens.
On this channels I have to add a recording on zattoo website and start the recorded show from kodi.

**Comment by rbuehlma** [comment]
Closing this due to not enough information. Feel free to re-open the issue with additional information.

**Comment by Mannshoch** [comment]
[kodi.zip](https://github.com/rbuehlma/pvr.zattoo/files/4103271/kodi.zip)

**Comment by rbuehlma** [comment]
Could you let me know which show on which channel you tried to watch with replay?

**Comment by Mannshoch** [comment]
"Mord ist ihr Hobby" on "Sat.1 Gold HD"

**Comment by rbuehlma** [comment]
I could reproduce this error and will try to find the root cause.

**Comment by rbuehlma** [comment]
This was a problem in the EPG service and should be solved now. As soons as you EPG gets updated, replay and recording should work.

**Comment by Mannshoch** [comment]
Was that an error you had to report to zattoo?

**Comment by rbuehlma** [comment]
The problem was in the alternative EPG service not on Zattoo side.

**Comment by Mannshoch** [comment]
Ah interesting, I thought that your app use also Zattoo for the EPG service.

**Comment by rbuehlma** [comment]
By default it does, but you can activate the "Enhanced EPG service" which collects the data from Zattoo and then provides this data to Kodi in a more efficient way. This is the service I am running. For both cases the original EPG source is Zattoo.
