### ISSUE TITLE
Login with 1&1 Account

### ISSUE THREAD

**Issue by foobar26** [rbuehlma/pvr.zattoo#72]
Login with third party provider 1&1 doesn't work and produces a 400.
HAL attached (I replaced user/password of working login).
System: LibreELEC 9.2.0, Kodi 18.5, pvr.zattoo 18.1.11.1

[www.1und1.tv.har.zip](https://github.com/rbuehlma/pvr.zattoo/files/4184956/www.1und1.tv.har.zip)

**Comment by foobar26** [comment]
It seems that the issue is related to the kind of special characters used for the password. A minut (-) works, an exclamation (!) mark doesn't.

**Comment by rbuehlma** [comment]
Fixed in 18.1.13/19.2.10
