### ISSUE TITLE
Quickline new URL?

### ISSUE THREAD

**Issue by diego0815** [rbuehlma/pvr.zattoo#77]
Hello I'm a long time happy user of the Zattoo PVR addon with Zattoo, now I took a subscription with Quickline and cant log in, the Kodi Log gives me just this:
`2020-03-21 22:31:34.412 T:5744  NOTICE: AddOnLog: Zattoo PVR Client: Using useragent: Kodi/19.0 pvr.zattoo/19.2.11 (Kodi PVR addon)
2020-03-21 22:31:35.216 T:5744   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 503
2020-03-21 22:31:35.216 T:5744   ERROR: CCurlFile::Open failed with code 503 for https://mobiltv.quickline.com/zapi/v2/account/login:
2020-03-21 22:31:35.216 T:5744   ERROR: AddOnLog: Zattoo PVR Client: Login failed.`

when trying to log in over quickline's URL https://mobiltv.quickline.com/, as used in ZatData.cpp line 569 with my browser, I also get a wrong PW notice, however it is possible to log in on the other address from the Quickline Page: https://content.quickline.ch/QuicklineWeb/

I can log in with my User and PW, but I get the following message:

```
Willkommen beim neuen Quickline TV
Sie profitieren jetzt von unserer neuen Web-App, die Ihr Fernseherlebnis einfacher und flexibler macht. Leider sind noch nicht alle Funktionen umgebaut. Wir arbeiten jedoch mit Hochdruck dran und bitten Sie um Verständnis.
Folgende Funktionen sind davon betroffen:
search
Suche: Die Suchfunktion ist leider noch nicht verfügbar.

search
Senderlisten: Das Erstellen von Senderlisten und die Anzeige von gespeicherten Senderlisten ist noch nicht möglich.

Zusatzpakete
Zusatzpakete: Ihre Abonnemente - mit Ausnahme der MySports-Sender – können Sie momentan nur auf der Quickline TV-Box und auf den Quickline Mobile Apps geniessen.

ticket
Tagestickets MySports: Sind zur Zeit nur über das Quickline Cockpit erhältlich.

CromeCast
Airplay- und Chromecast-Streaming: Integrieren wir noch.

browser
Browserunterstützung: Die App ist optimiert für Google Chrome und Safari. Firefox und Edge folgen so bald wie möglich.

Zusätzlich werden laufend weitere Funktionalitäten und Verbesserungen implementiert.

Vielen Dank für Ihre Geduld und Ihr Verständnis!

```
after that It asks to complete some profile and then asks about adding the device to the approved devices list.

Do you think it is feasible to get Quickline up and running again? or is it just me who is having this problem?

Please let me know if I can help with anything, logs, screenshots, tests, anything.

**Comment by rbuehlma** [comment]
The new URL does not use the Zattoo API anymore (at least not for the login). I fear there is nothing I can you in this addon. Someone would need to write a new Addon for Quickline.

**Comment by diego0815** [comment]
Thanks for the quick reply.

That's what I feared...
I will see if I get the old Zattoo based thing to run, as this is still in the online cockpit but refuses all logins. maybe will call them to ask.

should we close the issue for now?

**Comment by rbuehlma** [comment]
We can leave it open until we know if Quickline needs to be removed from the supported Resellers. Can you update the ticket as soon as you know more?

**Comment by diego0815** [comment]
Sure will have to find out. This new thing is quite annoying, app and
online, no way to scroll around in time in epg you have to enter the exact
time. I wish I could use zattoo instead.

Somewhere I read something about API 3.something in the URL, so maybe
zattoo is transitioning to something new?

I will definitely keep this ticket up to date once I found out more.

**Comment by diego0815** [comment]
I finally received the answer from Quickline:

Sehr geehrter Herr ...

Das Verte Login steht nur Verte Kunden zur Verfügung. Dies wird im Laufe des Jahres deaktiviert. Verte ist schon 2 Generationen älter als das aktuelle TV. Das werden Sie nicht nutzen können.

Wenn ich es aber richtig verstehe, läuft aber das aktuelle login?

https://content.quickline.ch/QuicklineWeb/#/

 

Beste Grüsse

seems like next year Quickline shuts definitely down the zattoo compatible TV for good

**Comment by rbuehlma** [comment]
Thanks for the update. In this case there is not much I can do in this addon. I therefore close this ticket.

**Comment by diego0815** [comment]
I will reopen this ticket once I see the Verte TV is gone from their logins page.
