### ISSUE TITLE
Zattoo not workinganymore

### ISSUE THREAD

**Issue by ivoruetsche** [rbuehlma/pvr.zattoo#81]
Since today (maybe since this week), the plugin is not working anymore. Just a red cross onthr top right corner.
On two Raspi's and on an Ubuntu installation.

Any Idea about?

**Comment by rbuehlma** [comment]
This is already fixed in the current version. On Ubuntu the PPA already contains the update. For the Raspi, you well need check with your image source to update the addon.

**Comment by ivoruetsche** [comment]
Thank a lot, Ubuntu is working now :-)

I use LibreELEC on the Raspi's

Vilä dank!
