### ISSUE TITLE
Thanks for maintaining this

### ISSUE THREAD

**Issue by ArnoldSchiller** [rbuehlma/pvr.zattoo#82]
The plugin on kodinerds didn't work anymore because of zapi/v2/... so I tried it from this git. Ok - a crosscompileswitch would be nice - the compilate from the PC didn't work at first, so I just compiled it on the pi4, that worked. Another point - I don't know how difficult it would be to integrate code from Zattoo HIQ into it - Zattoo HIQ as a video addon can also do teletext

Anyway, thank you very much for all the effort and work.

PS: Aber ich sehe schon HiQ ist Python und das hier ist C - so einfach wird das wohl doch nicht:
https://github.com/vaginessa/plugin.video.zattooHiQ/blob/stable/resources/teletext.py

**Comment by rbuehlma** [comment]
The build process for this addon is implemented in Kodi itself. I know that it is possible to cross compile Kodi itself and therefore also assume that it is possible to cross compile a PVR addon but no idea how to do it. Maybe it would be a good idea to ask in the Kodi forum: forum.kodi.tv

As for teletext: A PVR addon is limited to what the Kodi PVR API allows. Displaying a website (this is what teletext in case of Zattoo is) is not possible.
