### ISSUE TITLE
Replay only works for 1-2 days

### ISSUE THREAD

**Issue by madsci** [rbuehlma/pvr.zattoo#87]
Hi rbuehlma
I have been using your pvr addon daily and I am very happy to have it..
Due to login issues, I have switched from LibreElec stable 9.2.1 to Milhouse testbuilds for Kodi Matrix on RPi4.

Glad, with the update login and playback is again working normally. Unfortunately, replay has been only working for about 1-2 days until broadcast is not starting with error "File cannot be played. See log file".

In kodi log is no entry found

Settings in addon:
Provider Zattoo
Stream type dash
Allow providing zattoo session to service yes
Use enhanced epg service yes

Switching both to no does not help. Normally clearing epg data followed by reboot helps.
The issue is still on milhouse test build 4.23, the current one.

Thank you for your effort

**Comment by madsci** [comment]
Debug log with several attempts to play a replay broadcast.
http://ix.io/2jga

**Comment by rbuehlma** [comment]
`AddOnLog: Zattoo PVR Client: Recall is enabled for 0 seconds.`
This is a bit strange. Which type of account do you have?

Could you login with your browser and send me the content of https://zattoo.com/zapi/v2/session
SInce this contains some personal data, you might want to send it to me directly.

**Comment by madsci** [comment]
I am using a Zattoo Premium account. The detailed info is sent to you by PM

**Comment by madsci** [comment]
Interestingly, the following broadcast <https://zattoo.com/zapi/watch/recall/nick/182829906> worked yesterday evening. When I open the URL logged in with my credentials on my browser now, it only says "The path '/zapi/watch/recall/nick/182829906' was not found." (Error 404)
It seems that the replyTV entry points change frequently.

**Comment by rbuehlma** [comment]
The EPG is cached for quite some time (1-2 days). To protect the tv provider, reducing the cache is not really an option. If during this time, the id of a broadcasting changes, that would explain why it is not possible to replay this broadcasting. Does this affect you on only some broadcastings/channels or are all affected?

**Comment by madsci** [comment]
Indeed, I have the feeling that some channels (e.g. SRF 1, 2 & Info) are more affected than others (for instance KIKA or super rtl CH). Within a channel the different broadcast behave less frequent differently.

**Comment by rbuehlma** [comment]
Could you try the next time if you can reproduce this issue when not using the external EPG service? I would like to know if it is an issue in that service?

**Comment by madsci** [comment]
Good point. To clarify, first epg  option is 'on' and the second 'off'?

**Comment by rbuehlma** [comment]
only if both options are on, the external service is used. if one of them is off, the EPG is fetched directly from Zattoo. So yes, second option off is fine.

**Comment by madsci** [comment]
Hi rbuehlma
I can confirm, it is your external epg service, which makes troubles. With only first option active, reply TV has been working for a week without issues. As soon as the second option has been set as well, reply TV stopped playing on SRF 1 within one day.
I switched off external epg service, deleted all kodi epg data and after a reboot, reply TV was fine again.

**Comment by rbuehlma** [comment]
I hope I finally found the cause of this error and fixed it in the external EPG service. If you want to, you can now try to re-enable it.

**Comment by madsci** [comment]
Hi RBuehlma

Herzlichen Dank für die Behebung des Fehlers. Das ReplayTV läuft wieder 
seit Freitag auch auf "External EPG" einwandfrei bis auf eine Ausnahme. 
Für RTLPlus bekomme ich nun gar kein EPG mehr. Konnte dies bis jetzt 
nicht selbst testen. Heute Abend werde ich versuchen den EPG Cache zu 
löschen.

Freundliche Grüsse
David Rütti

Am 2020-06-17 08:47, schrieb rbuehlma:
