### ISSUE TITLE
Dolby not working for recordings

### ISSUE THREAD

**Issue by llave2** [rbuehlma/pvr.zattoo#91]
hello. I am getting the Dolby DD+ audio for live broadcast but for recordings I am only getting AAC.
I am using premium account, I hope you can fix that little problem, thanks
Thank you for your effort

**Comment by rbuehlma** [comment]
Are you sure that Dolby is supported for recordings? If yes, I do not know how the URL needs to be set to get the Dolby stream.

**Comment by rbuehlma** [comment]
Closing issue due to no feedback.
