### ISSUE TITLE
Since yesterday, Problem with 1und1 TV, unable to find Token

### ISSUE THREAD

**Issue by HalliHalloSchatz** [rbuehlma/pvr.zattoo#96]
Since yesterday, the pvr zattoo addon get a Red X and would not start.
I have Update to latest Repo Version 18.1.18.

I found in the kodi log only this:
unable to find Token... *.json and so on. 
I have no idea, how I can copy the log from my Fire TV 4k Stick to my PC, sorry.

**Comment by rbuehlma** [comment]
This is fixed in  18.1.19

**Comment by repnz-scasb** [comment]
Happening again since maybe 1 week it seems:

ERROR: AddOnLog: Zattoo PVR Client: Unable to find token-*.json in /app-fceefecf7a898873afd8.js

Any help would be appreciated.

**Comment by rbuehlma** [comment]
This is already fixed in 18.1.23
