### ISSUE TITLE
Channel order

### ISSUE THREAD

**Issue by codingPF** [rbuehlma/pvr.zattoo#98]
Hi,

sorry for the question maybe it is obvious but i am new to this plugin.

Is there any way to adjust the channel sequence?

Thanks

**Comment by rbuehlma** [comment]
Kodi allows you to reorder the channels but unfortunately, this configuration is lost frequently probably due to a bug.

Zattoo allows you to create an ordered favorite list on their page. This order is then also used by the addon.

**Comment by codingPF** [comment]
Thank you for pointing out the options!

I tried doing it via Settings>pvr>channel manager
It worked well for 2 days...afterwards everything was messed up

I will try the favorite option now
