### ISSUE TITLE
Timeshift for 1&1 not working

### ISSUE THREAD

**Issue by codingPF** [rbuehlma/pvr.zattoo#99]
First of all...thanks for the plugin....it’s working fine since a week!

I am quite new to the plugin do I was wondering what is possible and what just simply is not....therefore please excuse maybe obvious questions.

Back to my initial question....I noted that timeshift is not working properly (it abort after a minute)...is this something related to the addon or to the service (1&1 in this case)?

Thanks!

**Comment by rbuehlma** [comment]
Are you referring to replay tv (watching a past broadcast) or actually time shift (starting with the live stream an pausing or skipping backwards)?
Also please prove a complete debug log.

**Comment by codingPF** [comment]
This is about live tv...push pause button....wait about 50 sec...push the play button again.
Stream starts again (correct possition) but after 5-10 sec the stream moves to current (actual live tv) position. Kodi screen controlls still show a timeshift time but actual tv stream was reset to live.
[Log](https://pastebin.com/HVe72Tdw)

**Comment by rbuehlma** [comment]
Unfortunately, the log is not complete. Please provide a log containing all the information from startup until reproduction of the issue.

**Comment by codingPF** [comment]
Here you go [FULL LOG](https://pastebin.com/LBNw5nGZ)

**Comment by rbuehlma** [comment]
You are currently using "hls" as stream type in the settings of the addon. Could you change that to using "dash"? This could help with you issue

**Comment by codingPF** [comment]
Still the same issue. Please see [here](https://pastebin.com/r5TttN2e)

**Comment by rbuehlma** [comment]
Do you have timeshift available when watching in their page directly?

**Comment by codingPF** [comment]
Never really used it...first impression...yes it works

It is a bit strange since it seems to jump back some seconds when releasing pause but it works quite solid.

**Comment by rbuehlma** [comment]
Could you login using the page and send me to content of https://www.1und1.tv/zapi/v2/session. You may want to send it only to me since it might contain some personal data.

**Comment by codingPF** [comment]
After investigation it seems like this is some issue with 1&1 which can not be resolved

**Comment by rbuehlma** [comment]
Some more details: In case of 1&1, skipping in timeshift does not seem to be allowed. This is implemented by calling an endpoint on their backend upon pausing the stream. Unfortunately, the addon currently does not get any information on user interaction with the stream (like pausing the stream). This requires a change in the PVR api in Kodi.

**Comment by 4f1sh3r** [comment]
Since I can reproduce this error on all my RPis with a plain Zattoo account., I suggest to disable timeshift completely in the API? 
Currently it looks like the plugin would support it and a normal user just would want to use it. This could lead into frustrations.

This has happened with my wife last week: she pressed "Pause" in the good hope that it will work. When she finished her work and came back to the TV, she pressed "Resume" and after 1min, it jumped to the current position. This was frustrating for her. if she had known that, she would have let it run alongside instead of not watching it at all.
